[#arrays]
:imagesdir: chapters/arrays/images
:programsdir: chapters/arrays/programs
== Arrays

[quote, Mae West]
____
O excesso de algo bom pode ser maravilhoso.
____

=== Introdução

Com uma exceção, todos os tipos sobre os quais falamos neste livro
armazenam um único valor. Por exemplo, uma variável `int` só pode
conter um único valor `int`. Se você tentar inserir um segundo valor `int`
numa variável, ele substituirá o primeiro.

O tipo `String`, é claro, é a exceção. Objetos `String` podem
conter sequências `char` de qualquer comprimento, de 0 até um tamanho praticamente
ilimitado (o comprimento máximo teórico de um `String` em Java é
`Integer.MAX_INT`, mais de 650 vezes o comprimento de _Guerra e Paz_).
Por mais notáveis que sejam os objetos `String`, este capítulo trata de um tipo mais
geral de lista chamado _array_. Podemos criar arrays para armazenar uma
lista de qualquer tipo de variável em Java.

A capacidade de trabalhar com listas amplia o escopo dos problemas que podemos
resolver. Além de listas simples, podemos usar as mesmas ferramentas para criar tabelas,
grades e outras estruturas para resolver problemas fascinantes como o que
vem a seguir.

=== Problema: Jogo da Vida

Alguns físicos insistem que as regras que regem o universo são
terrivelmente complicadas. Outros insistem que as leis fundamentais são simples
e que apenas a interação global entre elas é complexa. Com a capacidade de realizar
simulações rapidamente, os cientistas da computação demonstraram que alguns sistemas
podem apresentar interações muito complexas utilizando regras simples. Talvez os
exemplos mais conhecidos desses sistemas sejam os _autômatos celulares_, dos quais
o Jogo da Vida de Conway é o mais famoso.

A estrutura do Jogo da Vida de Conway é uma grade infinita composta por
quadrados chamados células. Algumas células na grade são pretas (ou vivas, para
dar um toque biológico), e o restante é branco (ou morto). Qualquer
célula tem 8 vizinhas, conforme mostrado na figura abaixo.

[.text-center]
.Célula (mostrada em cinza) cercada por 8 células vizinhas.
image::cell.svg[scaledwidth=25%,pdfwidth=25%,width=25%,align="center"]

O padrão de células vivas e mortas em um determinado momento na grade é
chamado de _geração_. Para determinar a próxima geração, usamos as
seguintes regras.

1. Se uma célula viva tiver menos de dois vizinhos vivos, ela morre de
solidão.
2. Se uma célula viva tiver mais de três vizinhos, ela morre por causa da
superlotação.
3. Se uma célula viva tiver exatamente dois ou três vizinhos vivos, ela sobrevive
até a próxima geração.
4. Se uma célula morta tiver exatamente três vizinhas vivas, ela se torna uma
célula viva.

Essas quatro regras simples permitem interações mais complexas do que você poderia imaginar.
Os padrões que surgem da aplicação dessas regras a uma
configuração inicial de células vivas e mortas estabelecem um equilíbrio entre o caos
total e a ordem rígida. Como o nome do jogo sugere, a semelhança
com padrões biológicos de desenvolvimento pode ser surpreendente.

Sua tarefa é criar um simulador de Life de tamanho _n_ × _m_,
cujos valores específicos serão discutidos a seguir. O
programa deve simular o processo a uma velocidade que seja envolvente de
se assistir, com uma nova geração a cada décimo de segundo. O programa deve
começar tornando aleatoriamente 10% de todas as células vivas e o restante morto.

==== Limitações do terminal

Um problema que talvez esteja te preocupando é como exibir a
simulação. Em <<gui#gui>>, você aprenderá a criar uma interface gráfica de usuário (GUI)
capaz de exibir uma grade de células em preto e branco e muitas outras
coisas interessantes também. Por enquanto, a principal ferramenta que podemos usar para
saída ainda é o terminal. O método de saída que recomendamos é imprimir
um asterisco (`'*\'`) para uma célula viva e um espaço (`' '`) para uma
morta. Dessa forma, você pode ver facilmente os padrões se formando na tela e
mudando com o tempo.

O terminal clássico não é muito grande. Por esse motivo, sugerimos que
você defina a altura da sua simulação para 24 linhas e a largura da sua
simulação para 80 colunas. Essas dimensões estão em conformidade com os tamanhos mais antigos
de terminais. Se a tela do seu terminal for muito maior, você pode alterar
a largura e a altura posteriormente para realizar uma simulação maior. Não importa o quão
grande seja a tela do jogo, o tamanho ideal do jogo.
Como nosso tamanho é tão limitado, precisamos lidar com o problema de uma célula na borda.
Qualquer coisa além dos limites deve ser considerada morta. Assim, uma célula bem na borda
da grade de simulação pode ter no máximo 5 vizinhos. Uma célula em um
dos quatro cantos pode ter apenas 3 vizinhos.

Para dar a aparência de transições suaves, você precisa imprimir
cada nova geração de células rapidamente e nos mesmos locais que
a geração anterior. Simplesmente imprimir um conjunto após o outro não
alcançará esse efeito, a menos que a tela do seu terminal tenha exatamente 24 linhas de altura.
Portanto, você precisará limpar a tela a cada vez. Em um esforço para ser
independente de plataforma, o Java não oferece uma maneira fácil de limpar a
tela do terminal. Um truque rápido e simples é simplesmente imprimir 100
linhas em branco antes de imprimir a próxima geração. Esse truque funcionará
desde que a altura do seu terminal não seja significativamente superior a 100 linhas.
Se for, você precisará imprimir um número maior de linhas em branco.

Por fim, você precisa esperar um breve intervalo de tempo entre as gerações para
que o usuário possa ver cada configuração antes que ela seja apagada e
substituída pela próxima. A maneira mais simples de fazer isso é fazer com que seu
programa entre em espera por um breve período de tempo, um décimo de segundo, como
sugerimos anteriormente. O código para fazer seu programa entrar em espera por esse período
de tempo é:

[source,java]
--- -
try { Thread.sleep(100);
} catch (InterruptedException e) {}
----

Explicaremos esse código com muito mais detalhes em <<concurrency#concurrency>>.
O item-chave de importância é o número passado para o método `sleep()`.
Esse valor é o número de milissegundos que você deseja que seu programa fique em espera.
100 milissegundos são, obviamente, um décimo de segundo.

Para simular o Jogo da Vida, precisamos armazenar informações,
ou seja, se as células estão vivas ou mortas, em uma grade. Primeiro, precisamos
discutir a tarefa mais simples de armazenar dados em uma lista.

=== Conceitos: Listas de dados

As listas de dados são de suma importância em muitas áreas diferentes da
vida: listas de compras, listas de itens a levar, listas de funcionários que trabalham em uma
empresa, agendas de endereços, listas dos dez melhores e muito mais. As listas são ainda mais
importantes na programação. Como você sabe, um dos grandes pontos fortes dos
computadores é a velocidade. Se tivermos uma longa lista de dados, podemos usar
essa velocidade para realizar operações em todos os dados rapidamente. Listas de contatos de e-mail
, entradas em um banco de dados e células em uma planilha são
apenas algumas das formas mais óbvias como as listas aparecem em
aplicativos de computador.

Mesmo em Java, há muitas maneiras diferentes de registrar uma lista de
informações, mas uma lista é apenas uma forma de _estrutura de dados_. Como o
nome indica, uma estrutura de dados é uma maneira de organizar dados, seja em uma
lista, em uma árvore, em ordem classificada, em algum tipo de hierarquia ou de qualquer
outra forma que possa ser útil. Neste capítulo, falaremos apenas sobre a 
estrutura de dados de matriz, mas outras estruturas de dados serão discutidas
em <<dynamic-data-structures#dynamic-data-structures>>.
Abaixo, apresentamos uma breve explicação de alguns dos atributos que qualquer
estrutura de dados pode ter.

==== Atributo da estrutura de dados

Conteúdo:::
  Manter apenas um único valor em uma estrutura de dados vai contra o propósito de
  uma estrutura de dados. Mas, se podemos armazenar mais de um valor, será que
  todos esses valores devem ser do mesmo tipo? Se uma estrutura de dados pode
  conter vários tipos diferentes de dados, chamamos-na de _heterogênea_, mas
  se ela puder conter apenas um tipo, chamamos-na de _homogênea_.
Tamanho:::
O tamanho de uma estrutura de dados pode ser algo fixo no momento em que é
criada ou pode mudar dinamicamente. Se o tamanho ou
comprimento de uma estrutura de dados pode mudar, chamamos-a de estrutura de dados _dinâmica_. Se a estrutura de dados
tem um tamanho ou comprimento que nunca pode mudar após ter sido
criada, chamamos-a de estrutura de dados _estática_.
Acesso a Elementos:::
  Uma das razões pelas quais existem tantas estruturas de dados diferentes é que
  diferentes formas de estruturar dados são melhores ou piores para uma determinada
  tarefa. Por exemplo, se sua tarefa for adicionar uma lista de números, então
  você espera acessar cada elemento da lista. No entanto, se
  você estiver procurando uma palavra em um dicionário, não vai querer verificar
  todas as entradas do dicionário para encontrá-la. +
{empty} +
  Algumas estruturas de dados são otimizadas para que você possa ler,
  inserir ou excluir com eficiência apenas um único item, geralmente o primeiro (ou último) item
  na estrutura de dados. Algumas estruturas de dados permitem apenas que você se desloque
  pela estrutura sequencialmente, um item após o outro. Tal
  estrutura de dados possui o que se chama de _acesso sequencial_. Outras ainda
  permitem que você salte aleatoriamente para qualquer ponto que desejar dentro da estrutura de dados
  de forma eficiente. Essas estruturas de dados possuem o que se chama de
  _acesso aleatório_. Programadores avançados levam em consideração muitos fatores diferentes
  antes de decidir qual estrutura de dados é mais adequada para o seu
  problema.

==== Características de um vetor

Agora que definimos esses atributos, podemos dizer que um vetor é uma
estrutura de dados homogênea e estática com acesso aleatório. Um vetor é
homogêneo porque só pode conter uma lista de um único tipo de dados,
como `int`, `double` ou `String`. Um vetor é estático porque tem
um comprimento fixo que é definido apenas quando o vetor é instanciado. 
Um array
também possui acesso aleatório porque saltar para qualquer elemento no array é
rápido e leva aproximadamente o mesmo tempo que saltar para qualquer
outro.

Um array é uma lista de um tipo específico de elementos que tem comprimento
_n_, um comprimento especificado quando o array é criado. Cada um dos
_n_ elementos é indexado usando um número entre 0 e
_n_ - 1].
 Mais uma vez, a contagem baseada em zero mostra sua face feia
. Considere a seguinte lista de itens: {9, 4, 2, 1, 6, 8, 3}

Se essa lista for armazenada em um array, o primeiro elemento, 9,
teria o índice 0, 4 teria o índice
1, e assim por diante, terminando em 3 com um índice
de 6, embora o número total de itens seja
7. Nem todas as linguagens usam contagem baseada em zero para índices de vetor
, mas muitas o fazem, incluindo C, {cpp} e Java. A razão pela qual
linguagens como C originalmente usavam contagem baseada em zero para índices é que
a variável correspondente ao vetor é um endereço dentro da
memória do computador que aponta para o primeiro elemento da vetor. Assim, um índice
de 0 é 0 vezes o tamanho de um elemento somado ao endereço inicial,
e um índice de 5 é 5 vezes o tamanho de um elemento somado ao
endereço inicial. Portanto, os índices baseados em zero proporcionavam uma maneira rápida para o
programa calcular em que ponto da memória um determinado elemento de um array se encontrava.

=== Sintaxe: Arrays em Java

O conceito de lista não é nada misterioso. Numerar cada elemento da lista
é algo natural, mesmo que a numeração comece no 0 em vez de no 1.
No entanto, os arrays são a fonte de muitos erros que fazem com que os programas Java
travem. Abaixo, explicamos os fundamentos da criação de arrays, indexação em
arrays e uso de arrays com laços. Em seguida, há uma subseção extra
explicando como enviar dados de um arquivo para um programa como se o arquivo estivesse
sendo digitado por um usuário. Usar essa técnica pode economizar muito
tempo quando você estiver experimentando com arrays.

==== Declaração e instanciação de um array

Para criar um array, geralmente é necessário criar primeiro uma variável de array.
Lembre-se de que um array é uma estrutura de dados homogênea, o que significa que ele
só pode armazenar elementos de um único tipo. Ao criar uma variável de array
, você precisa especificar qual é esse tipo. Para declarar uma variável de
array, use o tipo que ela irá conter, seguido de colchetes
(`[]`), seguido do nome da variável. Por exemplo, se
você quiser criar um array chamado `numbers` que possa conter inteiros, você
digitaria o seguinte.

[source,java]
----
int[] numbers;
----

Se você tem alguma experiência em programação em C ou {cpp}, talvez esteja acostumado a
ver os colchetes do outro lado da variável, assim.

[source,java]
----
int numbers[];
----

Em Java, ambas as declarações são perfeitamente válidas e equivalentes. No entanto,
a primeira declaração é preferível do ponto de vista estilístico. Ela
segue o padrão de usar o tipo (um array de valores `int`, neste
caso) seguido pelo nome da variável como sintaxe para uma declaração.

Como dissemos, os arrays também são estruturas de dados estáticas, o que significa que seu
comprimento é fixado no momento da criação. No entanto, não especificamos um
comprimento acima. Essa declaração ainda não criou um array, apenas uma
variável que pode apontar para um array. Na segunda metade deste capítulo,
discutiremos mais detalhadamente essa diferença entre a maneira como um array é
criado e a maneira como um `int` ou qualquer outra variável de tipo primitivo é
criada. Para realmente criar o array, precisamos usar outra etapa,
envolvendo a palavra-chave `new`. Veja como instanciamos uma matriz do tipo 
`int` com 10 elementos.

[fonte,java]
----
numbers = new int[10];
----

Usamos a palavra-chave `new`, seguida do tipo de elemento, seguida
do número de elementos que o array pode conter entre colchetes. Esse novo
array é armazenado em `numbers`. Em outras palavras, a variável `numbers`
é agora um nome para o array. Normalmente, as duas etapas de declarar e
instanciar um array serão combinadas em uma única linha de código.

[source,java]
----
int[] numbers = new int[10];
----

É sempre possível separar as duas etapas. Em alguns casos, uma única
variável pode ser usada para apontar para um array de um comprimento específico,
depois alterada para apontar para um array de outro comprimento, e assim por diante, como
mostrado abaixo.

[source,java]
----
int[] numbers;
numbers = new int[10];
numbers = new int[100];
numbers = new int[1000];
----

Aqui, a variável `numbers` começa sem apontar para nenhum array. Em seguida, ela é
configurada para apontar para um novo array com 10 elementos. Depois, ela é configurada para
apontar para um novo array com 100 elementos, ignorando o array de 10 elementos.
Por fim, ela é configurada para apontar para um array com 1.000 elementos, ignorando
o array de 100 elementos. Lembre-se de que os próprios arrays são estáticos; seus
comprimentos não podem mudar. As variáveis do tipo array, no entanto, podem apontar para
diferentes arrays com comprimentos diferentes, desde que ainda sejam
do tipo correto (neste caso, arrays de valores `int`).

Quais valores estão dentro do array quando ele é criado pela primeira vez? Vamos voltar
ao caso em que `numbers` aponta para um novo array com 10 elementos. Cada
um desses elementos contém o valor `int` `0`, conforme mostrado abaixo.

[.text-center]
.Elementos do array mostrando valores de índice.
image::array.svg[scaledwidth=75%,pdfwidth=75%,width=75%,align="center"]


Sempre que um array é instanciado, cada um de seus _n_ elementos
é definido com algum valor padrão. Para `int`, `long`, `short` e `byte`
esse valor é `0`. Para `double` e `float`, esse valor é `0.0`. Para
`char`, esse valor é `'\0'`, um caractere especial não imprimível. Para
`boolean`, esse valor é `false`. Para `String` ou qualquer outro tipo de referência
, esse valor é `null`, um valor especial que significa que não há
objeto.

Também é possível usar uma lista para inicializar um array. Por exemplo,
podemos criar um array do tipo `double` que contenha os valores `0.5`,
`1.0`, `1.5`, `2.0` e `2.5` usando o código a seguir.

[source,java]
----
double[] increments = {0.5, 1.0, 1.5, 2.0, 2.5};
----

Esta linha de código é equivalente a usar a palavra-chave `new` para criar um
vetor `double` com 5 elementos e, em seguida, definir cada um com os valores
mostrados.

==== Acessando índices em arrays

Para usar um valor em um array, você deve acessar o índice do array, utilizando
novamente os colchetes. Voltando ao exemplo do array `int`
`numbers` com comprimento 10, podemos ler o valor no índice 4 do
array e exibi-lo.

[source,java]
----
System.out.println(numbers[4]);
----

Até que algum outro valor seja armazenado ali, o valor de `numbers[4]` é `0`,
e, portanto, `0` é tudo o que será impresso.
Podemos definir o valor em `numbers[4]` como `17` da seguinte maneira.

[source,java]
----
numbers[4] = 17;
----

Então, se tentarmos imprimir `numbers[4]`, `17` será impresso. O
conteúdo do array `numbers` ficará assim.

[.text-center]
.Array mostrando o conteúdo dos elementos.
image::array2.svg[scaledwidth=75%,pdfwidth=75%,width=75%,align="center"]


O ponto-chave a entender sobre a indexação em um array é que ela
fornece um elemento do tipo especificado. Em outras palavras, `numbers[4]`
*é* uma variável `int` em todos os sentidos possíveis. Você pode ler seu valor.
Você pode alterar seu valor. Você pode passá-lo para um método. Ele pode ser usado
em qualquer lugar onde um `int` normal possa ser usado, como no exemplo a seguir.

[source,java]
----
int x = numbers[4];
double y = Math.sqrt(numbers[2]) + numbers[4];
numbers[9] = (int)(y*x);
----

A execução deste código armazenará `17` em `x` e `17.0` em `y`. Em seguida,
o produto desses dois, `289`, será armazenado em `numbers[9]`.
Lembre-se: em Java, o tipo à esquerda e o tipo à direita do
operador de atribuição (`=`) devem coincidir, exceto em casos de conversão automática
, como armazenar um valor `int` em uma variável `double`. Como
eles têm o mesmo tipo, faz sentido armazenar um elemento de uma matriz `int`
como `numbers[4]` em uma variável `int` como `x`. No entanto, um
array de valores `int` *não pode* ser armazenada em um tipo `int`.

[source,java]
----
int z = numbers;
----

Este código causará um erro de compilação. O que isso significa? Você não pode colocar
uma lista de variáveis em uma única variável. E o inverso também é verdadeiro
.

[source,java]
----
numbers = 31;
----

Este código também causará um erro de compilação. Um único valor *não pode* ser
armazenado em uma lista inteira. Você teria que especificar um índice onde ele possa ser
armazenado. Além disso, você deve ter cuidado para especificar um índice válido. Nenhum
índice negativo será válido, nem um índice maior
ou igual ao número de elementos na matriz.

[source,java]
----
numbers[10] = 99;
----

Este código será compilado corretamente. Se você se lembra, instanciamos o
array para o qual `numbers` aponta para ter 10 elementos, numerados de 0 a
9. Assim, estamos tentando armazenar `99` no elemento que está um índice
*depois* do último elemento válido. Como resultado, o Java causará um erro
chamado `ArrayIndexOutOfBoundsException`, o que fará com que
seu programa trave.

==== Usando laços com arrays

Uma razão para usar arrays é evitar declarar 10 variáveis separadas
apenas para ter 10 valores `int` com os quais trabalhar. Mas, uma vez que você tenha o array,
muitas vezes precisará de uma maneira automatizada de processá-lo. Qualquer um dos três
tipos de laços oferece uma ferramenta poderosa para realizar operações em um
array, mas o laço `for` é especialmente adequado para isso. Aqui está um
exemplo de um laço `for` que define os valores em um array para seus
índices.

[source,java]
----
int[] values = new int[100];
for (int i = 0; i < 100; ++i) {
    values[i] = i;
}
----

Este exemplo de código mostra como é fácil iterar sobre todos os elementos
de um array com um laço `for`, no entanto, ele apresenta uma falha de estilo. Observe que
o número `100` é usado duas vezes: uma vez na instanciação do array
e uma segunda vez na condição de terminação do laço `for`. Este
fragmento de código funciona bem, mas se o programador alterar o comprimento de
`values` para `50` ou `500`, os limites do laço `for` também
precisarão ser alterados. Além disso, o comprimento do array pode ser determinado
pela entrada do usuário.

Para tornar o código mais robusto e legível, podemos usar o campo `length`
do array `values` como limite do laço `for`.

[source,java]
----
int[] values = new int[100];
for (int i = 0; i < values.length; ++i) {
    values[i] = i;
}
----

O campo `length` fornece o comprimento do array que `values` aponta
. Se o programador quiser instanciar o array com um comprimento diferente
, tudo bem. O campo `length` sempre refletirá o 
valor correto. Sempre que possível, use o campo `length` dos arrays em seu código.
Observe que o campo `length` é somente leitura. Se você tentar definir
`values.length` com um valor específico, seu código não será compilado.

Definir os valores em um array é apenas uma das tarefas possíveis que você pode realizar
com um laço. Vamos supor que um array do tipo `double` chamado `data`
tenha sido declarado, instanciado e preenchido com a entrada do usuário. Poderíamos
somar todos os seus elementos usando o código a seguir. Uma maneira mais elegante de fazer
a mesma soma é discutida em <<Laços `for` aprimorados>>.

[source,java]
----
double sum = 0.0;
for (int i = 0; i < data.length; ++i) {
    sum += data[i];
}
System.out.println("A soma dos seus dados é: " + sum);
----

Até agora, discutimos apenas operações sobre os *valores* em um array. É
importante perceber que a *ordem* desses valores pode ser igualmente
importante. Vamos criar um array do tipo `char` chamado
`letters`, inicializado com alguns valores, e depois inverter a ordem do
array.

[source,java]
----
char[] letters = {'b', 'y', 'z', 'a', 'n', 't', 'i', 'n', 'e'}; // <1>
int start = 0; // <2>
int end = letters.length - 1; // <3>
char temp;
while (start < end) { // <4>
    temp = letters[start]; // <5>
    letters[start] = letters[end];
    letters[end] = temp;
    ++start; // <6>
    --end;
}
for (int i = 0; i < letters.length; ++i) { //<7>
    System.out.print(letters[i]);
}
----

<1> Após inicializar o array `letters`
, declaramos `start` e `end`.
`start` recebe o valor `0`, o
primeiro índice de `letters`.
`end` recebe o valor `letters.length - 1`, o último índice válido
de `letters`.
O laço `while` continua enquanto
`start` for menor que `end`.
<2> As três primeiras linhas de cada
iteração do laço `while` trocam o `char` no índice `start` pelo
`char` no índice `end`.
<3> As duas linhas seguintes incrementam e
decrementam `start` e `end`, respectivamente. Quando os dois se encontram no
meio, toda o array foi invertido.
<4> O laço `for` simples no
final imprime cada `char` em `letters`, gerando a saída `enitnazyb`.

É claro que poderíamos ter
impresso os elementos do array na ordem inversa sem alterar sua
ordem, mas queríamos invertê-los, talvez porque precisaremos deles
invertidos no futuro.

==== Redirecionando a entrada

Com arrays e laços, podemos processar uma grande quantidade de dados, mas testar
programas que processam muitos dados pode ser tedioso. Em vez de digitar
os dados no terminal, podemos lê-los a partir de um arquivo. Em Java, a E/S de arquivos
é um processo complicado que envolve vários objetos e chamadas de métodos. Vamos
falar sobre isso em profundidade em <<file-io#file-io>>, mas, por
enquanto, podemos usar uma solução alternativa rápida e fácil.

Se você criar um arquivo de texto usando um editor de texto simples, poderá _redirecionar_
o arquivo como entrada para um programa. Tudo o que você escreveu no arquivo de texto
é tratado como se estivesse sendo digitado na linha de comando por uma
pessoa. Para fazer isso, digite o comando usando `java` para executar sua classe
normalmente, digite o sinal `<` e, em seguida, digite o nome do arquivo que você
deseja usar como entrada. Por exemplo, se você tiver um arquivo de texto chamado
`numbers.txt` que deseja usar como entrada para um programa armazenado em
`Summer.class`, você poderia fazer isso da seguinte maneira.

----
java Summer < numbers.txt
----

Redirecionar a entrada dessa maneira não faz parte do Java. Em vez disso, é um
recurso do terminal em execução no seu sistema operacional. Nem todos os sistemas operacionais
suportam redirecionamento de entrada, mas praticamente todas as versões do Linux e do Unix
suportam, assim como a linha de comando do Windows e o terminal do macOS. Nós
poderíamos escrever o programa mencionado acima e atribuir a ele a tarefa simples de
somar todos os números que receber como entrada.

.Soma uma lista de números fornecidos como entrada.
[source, java]
[[SummerProgram]]
----
include::{programsdir}/Summer.java[]
----

Agora, podemos criar um arquivo com uma lista de números e salvá-lo como
`numbers.txt`. Para estar em conformidade com o programa que escrevemos, devemos também colocar
a contagem total de números como o primeiro valor no arquivo. Você pode colocar
cada número em uma linha separada ou apenas deixar um espaço entre cada um.
Desde que estejam separados por espaços em branco, o objeto `Scanner` irá
cuidar do resto. Você terá que digitar os números no arquivo
uma vez, mas depois poderá testar seu programa repetidamente com o mesmo arquivo.

Se você executar o programa com o arquivo que criou, perceberá
que o programa ainda solicita uma vez a contagem total de números
e, em seguida, solicita várias vezes que você insira o próximo número. Com
entrada redirecionada, todo esse texto é processado de forma confusa. Toda a
entrada vem de `numbers.txt`. Se você espera que um programa leia
estritamente a partir da entrada redirecionada, pode projetar seu código de maneira um pouco
diferente. Por um lado, você não precisa de solicitações explícitas para
o usuário. Por outro lado, você pode usar vários métodos especiais da
classe `Scanner`. A classe `Scanner` possui vários métodos como
`hasNextInt()` e `hasNextDouble()`. Esses métodos examinam a
entrada e verificam se há outro `int` ou `double` válido, retornando
`true` ou `false` conforme o caso. Se você espera que um arquivo tenha apenas uma longa
sequência de valores `int`, pode usar `hasNextInt()` para determinar se
chegou ao fim do arquivo ou não. Usando `hasNextInt()`, podemos
simplificar o programa e remover a expectativa de que o primeiro número
forneça a contagem total de números.

.Soma uma lista de números fornecidos como entrada sem solicitar nada ao usuário.
[source, java]
[[QuietSummerProgram]]
----
include::{programsdir}/QuietSummer.java[]
----

Por outro lado, você pode estar interessado na saída de um programa.
A saída pode ser muito longa ou pode levar muito tempo para ser produzida
ou você pode querer armazená-la permanentemente. Para essas situações, é
possível _redirecionar a saída_ também. Em vez de imprimir na
tela, você pode enviar a saída para um arquivo de sua escolha. A sintaxe
para essa operação é igual à sintaxe para redirecionamento de entrada, exceto
que você usa o sinal `>` em vez de `<`. Para executar `QuietSummer` com
entrada de `numbers.txt` e saída para `sum.txt`, poderíamos fazer o
seguinte.

`java QuietSummer < numbers.txt > sum.txt`

Você pode examinar o `sum.txt` a qualquer momento com o editor de texto
de sua preferência. Ao usar o redirecionamento de saída, faz mais sentido executar
o `QuietSummer` do que o `Summer`. Se tivéssemos executado o `Summer`, toda aquela
saída desnecessária solicitando que o usuário insira números seria salva no
`sum.txt`.

=== Exemplos: uso dos arrays

Aqui estão alguns exemplos de uso prático dos arrays. Vamos
discutir algumas técnicas úteis principalmente para pesquisa e classificação.
Pesquisar valores em uma lista pode parecer algo rotineiro, mas é uma das tarefas mais
práticas que um cientista da computação realiza diariamente. Ao
fazer com que um computador faça esse trabalho, poupamos dos seres humanos inúmeras horas de
pesquisas e verificações tediosas. Outra tarefa importante é a classificação.
Classificar uma lista pode tornar pesquisas futuras mais rápidas e é a maneira mais simples
de encontrar a mediana de uma lista de valores. A classificação é uma parte fundamental de
inúmeros problemas do mundo real.

Nos exemplos abaixo, discutiremos primeiro como encontrar o maior (ou
menor) valor em uma lista, passaremos para a classificação de listas e, em seguida, falaremos sobre
uma tarefa que pesquisa palavras, como uma consulta em um dicionário.

[[kingOfTheHillExample]]
.Rei da colina
====

Encontrar o maior valor inserido por um usuário não é difícil. Aplicar
esse conhecimento a um array também é bastante simples. Essa
tarefa simples também é um alicerce do algoritmo de classificação que discutiremos
abaixo. A chave para encontrar o maior valor em qualquer lista é
manter uma variável temporária que registre o maior valor encontrado até o momento.
À medida que avançamos, atualizamos a variável se encontrarmos um valor maior. O
único truque é inicializar a variável com algum valor inicial apropriado
. Poderíamos inicializá-la com zero, mas e se toda a lista de
números for negativa? Nesse caso, nossa resposta seria maior do que qualquer um dos
números da lista. Se nossa lista de números for do tipo `int`, poderíamos
inicializar nossa variável como `Integer.MIN_VALUE`, o menor
`int` possível. Essa abordagem funciona, mas você precisa se lembrar do nome da
constante, e isso não melhora a legibilidade do código.

Ao trabalhar com um array, a melhor maneira de encontrar o maior valor na
lista é definindo sua variável temporária como o primeiro elemento
(índice `0`) do array. Abaixo está um pequeno trecho de código que encontra
o maior valor em um array `int` chamado `values` exatamente dessa maneira.

[source,java]
----
int maior = valores[0];
for (int i = 1; i < valores.length; ++i) {
    if (valores[i] > maior) {
        maior = valores[i];
    }
}
System.out.println("O maior valor é " + maior);
----

Observe que o laço `for` começa em `1`, não em `0`. Como `largest` é
inicializado como `values[0]`, não há motivo para verificar esse valor uma segunda vez.
Fazer isso ainda daria a resposta correta, mas desperdiçaria uma pequena
quantidade de tempo.

Qual é a característica desse código que faz com que ele encontre o maior valor?
A chave é o operador `>`. Com a alteração de um único caractere,
poderíamos encontrar o menor valor em vez disso.

[source,java]
----
int menor = valores[0];
for (int i = 1; i < valores.length; ++i) {
    if (valores[i] < menor) {
        menor = valores[i];
    }
}
System.out.println("O menor valor é " + smallest);
----

Além da alteração necessária de `>` para `<`, também alteramos a
saída e o nome da variável para evitar confusão. Agora, vamos mostrar
como encontrar repetidamente o menor valor em um array pode ser usado para
ordená-lo. Alternativamente, o maior valor poderia ser usado igualmente bem.

====


[[selectionSortExample]]
.Classificação por seleção
====

A classificação é o pão com manteiga dos cientistas da computação. Muitas pesquisas
têm se dedicado a encontrar as maneiras mais rápidas de ordenar uma lista de dados. O
resto do mundo presume que ordenar uma lista de dados é trivial porque
os cientistas da computação fizeram um excelente trabalho ao resolver esse problema. O
nome do algoritmo de ordenação que descreveremos a seguir é
_ordenação por seleção_. Ela *não é* uma das maneiras mais rápidas de ordenar dados, mas
é simples e fácil de entender.

A ideia por trás da ordenação por seleção é encontrar o menor elemento em um
array e colocá-lo no índice `0` do array. Em seguida, a partir dos
elementos restantes, encontrar o menor elemento e colocá-lo no índice `1` do
array. O processo continua, preenchendo o array a partir do início
com os menores valores até que todo o array esteja ordenado. Se o comprimento
do array for _n_, precisaremos procurar o menor
elemento no array _n_ - 1 vezes. Ao colocar o código que
procura o menor valor dentro de um laço externo, podemos escrever um
programa que faça a ordenação por seleção de valores `int` inseridos pelo usuário da
seguinte forma. Este programa não é muito longo, mas há muita coisa acontecendo.

[source, java]
----
include::{programsdir}/SelectionSort.java[lines=1..12]
----
<.> Após
instanciar um `Scanner`, lemos o número total de valores que a
lista irá conter. Não podemos confiar no método `hasNextInt()` para nos dizer
quando parar de ler valores.
<.> Precisamos saber antecipadamente quantos valores
vamos armazenar para que possamos instanciar nosso array com o
comprimento apropriado.
<.> Em seguida, lemos cada valor no array usando o
primeiro laço `for`.

[source, java]
----
include::{programsdir}/SelectionSort.java[lines=13..23]
----
<.> O próximo laço `for` é onde a classificação propriamente dita ocorre. Começamos no índice
`0` e, em seguida, tentamos encontrar o menor valor para ser colocado nesse local.
Depois, passamos para o índice `1`, e assim por diante, exatamente como descrevemos anteriormente.
Observe que só vamos até `n - 2`. Não precisamos encontrar o valor a
ser colocado no índice `n - 1`, porque o restante da lista contém os `n - 1`
menores números e, portanto, o último número *deve* já ser o
maior.
<.> Se você observar com atenção, perceberá que o laço interno `for`
tem a mesma estrutura geral do laço usado para encontrar o menor
valor no exemplo anterior; no entanto, há uma diferença fundamental:
<.> Em vez de armazenar o *valor* do menor número em `smallest`, nós
agora armazenamos o *índice* do menor número. Precisamos armazenar o índice
do menor número para que, na próxima etapa, possamos trocar o
elemento correspondente com o elemento em `i`, o local no array
que estamos tentando preencher.
<.> As três linhas após o laço `for` interno são uma
troca simples para fazer exatamente isso.

[source, java]
----
include::{programsdir}/SelectionSort.java[lines=24..29]
----
<.> Depois que toda a classificação estiver concluída, o laço `for` final imprime a lista recém-
classificada.

Este programa não solicita nenhuma entrada do usuário, portanto, está bem
projetado para redirecionamento de entrada. Se você for criar um arquivo
contendo números que deseja classificar com este programa, certifique-se de que
o primeiro número seja a contagem total de números no arquivo.

Mais uma vez, este programa ordena a lista em ordem crescente (do menor para o
maior). Se você quisesse ordenar a lista em ordem decrescente,
bastaria alterar o `<` para um `>` na comparação do laço interno
`for`, embora outras alterações sejam recomendadas para facilitar a
legibilidade.

====

[[wordSearchExample]]
.Busca de palavras
====

Neste exemplo, lemos uma lista de palavras e uma longa passagem de
texto e registramos o número de vezes que cada palavra da lista aparece
na passagem. Esse tipo de pesquisa de texto tem muitas aplicações.
Ideias semelhantes são usadas em um corretor ortográfico que precisa consultar palavras em
um dicionário. As ferramentas de localização e substituição, incrivelmente valiosas nos modernos
processadores de texto, utilizam algumas dessas mesmas técnicas.

Para fazer este programa funcionar, no entanto, precisamos ler uma lista (potencialmente
longa) de palavras e, em seguida, uma grande quantidade de texto. Somos obrigados a usar redirecionamento de entrada
(ou alguma outra forma de entrada de arquivo) porque digitar esse texto
várias vezes seria tedioso. Quando chegarmos a <<file-io#file-io>>,
falaremos sobre maneiras de ler de vários arquivos ao mesmo
tempo. No momento, só podemos redirecionar a entrada de um único arquivo e, portanto,
somos obrigados a colocar a lista de palavras no início do arquivo, seguida pelo
texto que queremos pesquisar.

[source, java]
----
include::{programsdir}/WordCount.java[lines=1..12]
----
<.> Assim como no último exemplo, este programa começa lendo o comprimento da
lista de palavras.
<.> Em seguida, ele instancia o array `String` `words` para
armazenar essas palavras.
<.> Ele também instancia um array `counts` do tipo `int`
para acompanhar o número de vezes que cada palavra é encontrada. Por padrão,
cada elemento em `counts` é inicializado como `0`.
<.> O primeiro laço `for` no
programa lê cada palavra e a armazena no array `words`.

[source, java]
----
include::{programsdir}/WordCount.java[lines=13..21]
----
<.> O laço `while` lê cada palavra do texto que segue a lista e
a armazena em uma variável chamada `temp`.
<.> Em seguida, ele percorre `words`
e verifica se `temp` corresponde a algum dos elementos da lista.
<.> Se corresponder, ele aumenta o valor do elemento de `counts` que tem o
mesmo índice e sai do laço `for` interno.

[source, java]
----
include::{programsdir}/WordCount.java[lines=22..27]
----
<.> Depois que todas as palavras do texto forem processadas, o laço `for` final
imprime cada palavra da lista, juntamente com suas contagens.

Este programa usa dois arrays diferentes para registro: `words` contém
as palavras que estamos procurando e `counts` contém o número de vezes
que cada palavra foi encontrada. Esses dois arrays são estruturas de dados separadas.
A única ligação entre elas é o código que escrevemos para manter a
correspondência entre seus elementos.

Para dar uma ideia clara de como este programa deve se comportar, aqui está um
arquivo de entrada de exemplo com dois parágrafos do início de _O Conde
de Monte Cristo_, de Alexandre Dumas.

....
7
e
na
ponte
para
piloto
navio
noz
Em 24 de fevereiro de 1815, o vigia de Notre-Dame de la Garde sinalizou para o veleiro de três mastros, o Pharaon, proveniente de Esmirna, Trieste e Nápoles. Como de costume, um piloto partiu imediatamente e, contornando o Château d'If, embarcou no navio entre o Cabo Morgion e a ilha de Rion.

Imediatamente, e conforme o costume, as muralhas do Forte Saint-Jean ficaram repletas de espectadores; é sempre um evento em Marselha quando um navio entra no porto, especialmente quando esse navio, como o Pharaon, foi construído, equipado e carregado nas antigas docas de Foceia e pertence a um armador da cidade.
....

E aqui está a saída que se deve obter ao executar `WordCount` com
a entrada redirecionada do arquivo fornecido acima.

....
As contagens de palavras são:
e 6
em 3
ponte 0
para 1
piloto 1
navio 1
noz 0
....

Para este exemplo, o programa funciona bem. No entanto, nosso programa
teria gerado uma saída incorreta se `ship`, `spectators` ou várias outras
palavras no texto estivessem na lista de palavras. Veja bem, o método `next()`
na classe `Scanner` lê valores `String` separados por
espaços em branco. A palavra `ship` aparece duas vezes no texto, mas a segunda
ocorrência é seguida por uma vírgula. Como as palavras são separadas apenas por espaços em branco
, a `String` `"ship,"` não corresponde à `String` `"ship"`.
Lidar com pontuação não é difícil, mas aumentaria o
comprimento do código, então deixamos isso como um exercício.
====

****
<<wordSearchPunctuationExercise>>
****

[[statisticsExample]]
.Estatísticas
====

Imagine que você é um professor que acabou de aplicar uma prova. Você deseja
produzir estatísticas para a turma, para que os alunos tenham uma ideia de
como se saíram. Você quer escrever um programa em Java para ajudá-lo
a produzir as estatísticas, a fim de economizar tempo agora e no futuro.

As estatísticas que você deseja coletar estão listadas na tabela a seguir.

[.center%autowidth%unbreakable,cols="<,<"]
|===========================================================
|Estatística |Descrição

|Máximo |Pontuação máxima
|Mínimo |Pontuação mínima
|Média |Média de todas as pontuações
|Desvio Padrão |Desvio padrão amostral das pontuações
|Mediana |Valor central das pontuações quando ordenadas
|===========================================================

<<kingOfTheHillExample>> abordou como encontrar as pontuações máxima e
mínima em uma lista. A média é simplesmente a soma de todas as pontuações
dividida pelo número total de pontuações. O desvio padrão é um pouco
mais complicado. Ele fornece uma medida de quão dispersos os dados estão. Seja
_n_ o número de pontos de dados, denotemos cada ponto de dados como
_x_i_, onde 1 ≤ _i_ ≤ _n_, e seja
_μ_ a média de todos os pontos de dados. Então, a
fórmula para o desvio padrão amostral é a seguinte.

// [stem]
//++++
//\sigma = \sqrt{\frac{1}{n - 1}\sum_{i = 1}^n (x_i - \mu)^2}
//++++

[.text-center]
image::deviation.svg[scaledwidth=25%,pdfwidth=25%,width=25%,align="center"]

Por fim, se você classificar uma lista de números em ordem, a mediana é o
valor do meio da lista, ou a média dos dois valores do meio, se
a lista tiver um número par de elementos.

Esses tipos de operações estatísticas são úteis e estão integrados
em muitos aplicativos empresariais importantes, como o Microsoft Excel. Esta
versão terá uma interface simples cuja entrada é feita pela linha de comando
. Primeiro, o número total de pontuações será inserido. Em seguida, cada
pontuação deve ser inserida uma a uma. Depois que todos os dados forem inseridos,
o programa deve calcular e exibir os cinco valores.

Abaixo apresentamos a solução para este problema estatístico. Várias tarefas diferentes
são combinadas aqui, mas cada uma delas deve ser razoavelmente fácil de
resolver após os exemplos anteriores.

[source, java]
----
include::{programsdir}/Statistics.java[lines=1..10]
----
<.> Em nossa solução, o método `main()` começa lendo o
número total de pontuações.
<.> Ele declara um array `int` com esse comprimento chamado
`scores`.
<.> Em seguida, lemos cada uma das pontuações e as armazenamos em
`scores`.

[source, java]
----
include::{programsdir}/Statistics.java[lines=11..22]
----
<.> Aqui declaramos as variáveis `max`, `min` e `sum` para armazenar, respectivamente,
o máximo, o mínimo e a soma dos elementos do array. Em seguida, definimos
todas as três variáveis com o valor do primeiro elemento do array.
Essas inicializações fazem com que o código a seguir funcione.
<.> Em um único laço `for`
, encontramos o máximo, o mínimo e a soma de todos os valores no
array.

Poderíamos ter feito isso com três laços separados, mas esta
abordagem é mais eficiente. Definir `max` e `min` como `scores[0]`
segue o padrão que usamos anteriormente, mas definir `sum` com o mesmo
valor também é necessário neste caso. Como o laço itera de `1`
até `scores.length - 1`, devemos incluir o valor no índice `0` em
`sum`.
 Como alternativa, poderíamos ter definido `sum` como `0` e iniciado o
laço `for` em `i = 0`.

[source, java]
----
include::{programsdir}/Statistics.java[lines=23..26]
----

Neste pequeno trecho de código, calculamos a média, tomando o cuidado de
convertê-la para o tipo `double` antes da divisão, e então imprimimos as três
estatísticas que calculamos.

[source, java]
----
include::{programsdir}/Statistics.java[lines=27..32]
----
<.> Neste ponto, usamos a média que já calculamos para encontrar o
desvio padrão amostral. Seguindo a fórmula para o desvio padrão
amostral, subtraímos a média de cada pontuação, elevamos o resultado ao quadrado e
o adicionamos a um total acumulado. Embora a fórmula para o desvio padrão
amostral use os limites de 1 a _n_, nós
os convertemos de `0` a `n - 1` devido à numeração do array baseada em zero.
<.> Dividindo o total por `n - 1`, obtemos a variância amostral.
<.> Então, a
raiz quadrada da variância é o desvio padrão.

[source, java]
----
include::{programsdir}/Statistics.java[lines=33..44]
----
<.> Para encontrar a mediana, usamos nosso código de ordenação por seleção.

Observe que reutilizamos
a variável `min` para armazenar o menor valor encontrado até o momento,
em vez de declarar uma nova variável como `smallest`. Alguns programadores
podem se opor a isso, já que corremos o risco de interpretar a
variável como o valor mínimo em todo o array, como era antes.
Qualquer uma das abordagens está correta. Se você se preocupa em confundir quem estiver lendo
seu código, adicione um comentário.

[source, java]
----
include::{programsdir}/Statistics.java[lines=45..53]
----
<.> Depois que o array foi ordenado, precisamos fazer uma verificação rápida para ver se
seu comprimento é ímpar ou par.
<.> Se seu comprimento for par, precisamos encontrar a média dos dois elementos do meio.
<.> Se o comprimento for ímpar, podemos reportar o valor do único elemento do meio.

Observe que algumas das estatísticas que encontramos, como o máximo, o mínimo
ou a média, poderiam ser calculadas com uma única passagem pelos dados
sem a necessidade de um array para armazenamento.
No entanto, as duas últimas tarefas precisam armazenar todos os valores para funcionar.
A maneira mais simples de encontrar o desvio padrão amostral de uma lista de valores
requer sua média, exigindo uma passagem para encontrar a média e uma segunda
para somar os quadrados da diferença entre a média e cada valor.
Da mesma forma, é impossível encontrar a mediana de uma lista de valores sem
armazenar a lista.

****
<<modeExercise>>
****

====

=== Conceitos: Listas multidimensionais

Na primeira metade deste capítulo, focamos em listas de dados e em como
armazená-las em Java usando vetores. Os vetores que já discutimos
são vetores _unidimensionais_. Ou seja, cada elemento do vetor possui um
único índice que se refere a ele. Dado um índice específico, um elemento 
terá esse índice, virá antes dele ou virá depois dele. Esses tipos de vetores
podem ser usados para resolver um grande número de problemas envolvendo listas ou
coleções de dados.

Às vezes, os dados precisam ser representados com mais estrutura. Uma maneira
de fornecer essa estrutura é com uma matriz _bidimensional_. Você pode
pensar em uma matriz bidimensional como uma tabela de dados. Em vez de usar um
único índice, uma matriz bidimensional possui dois índices. Normalmente, pensamos
nessas dimensões como linhas e colunas. Abaixo está uma tabela de
informações que apresenta as distâncias em milhas entre as cinco maiores
cidades dos Estados Unidos.

[.center%autowidth%unbreakable,cols="^.^h,5*^.^",]
|==============================
| | Nova York | Los Angeles | Chicago | Houston | Phoenix

| Nova York |0 |2.791 |791 |1.632 |2.457
| Los Angeles |2.791 |0 |2.015 |1.546 |373
| Chicago |791 |2.015 |0 |1.801 |1.181
| Houston |1.632 |1.546 |1.801 |0 |1.176
| Phoenix |2.457 |373 |1.181 |1.176 |0
|==============================

A posição de cada número na tabela é uma parte fundamental de sua
utilidade. Sabemos que a distância de Chicago a Houston é de 1.801
milhas porque esse número está na linha de Chicago e na coluna de Houston.
Uma matriz bidimensional compartilha quase todas as suas propriedades com um
vetor unidimensional. Continua sendo uma estrutura de dados homogênea e estática
com acesso aleatório. Se o exemplo acima fosse transformado em uma matriz Java,
os próprios números seriam os elementos da matriz. Os nomes das
cidades precisariam ser armazenados separadamente, talvez em uma matriz do
tipo `String`.

Não há motivo para limitar a ideia de uma lista bidimensional a uma
tabela de valores. Muitos jogos são jogados em uma grade bidimensional. Um dos
jogos mais famosos desse tipo é o xadrez. Assim como em tantas outras coisas na
ciência da computação, precisamos criar uma abstração que reflita
a realidade e nos permita armazenar as informações dentro de um computador. Para
o xadrez, precisaremos de uma matriz bidimensional 8 × 8. Podemos representar
cada peça no tabuleiro com um `char`, usando a codificação fornecida abaixo.

[.center%autowidth%unbreakable,cols="^,^l"]
|===================
|Peça |Codificação

|Peão |'P'
|Cavalo |'N'
|Bispo |'B'
|Torre |'R'
|Rainha |'Q'
|Rei |'K'
|===================

Usando letras maiúsculas para as peças pretas e minúsculas
para as peças brancas, poderíamos representar uma partida de xadrez após uma clássica
abertura do peão do rei pelas brancas, conforme mostrado.

[.center%autowidth%unbreakable,cols="^.^h,8*^.^l",]
|=======================================================
| | 0 | 1 | 2| 3 | 4 | 5 | 6 | 7

| 0 |‘R’ |‘N’ |‘B’ |‘Q’ |‘K’ |‘B’ |‘N’ |‘R’
| 1 |‘P’ |‘P’ |‘P’ |‘P’ |‘P’ |‘P’ |‘P’ |‘P’
| 2 | | | | | | | |
| 3 | | | | | | | |
| 4 | | | | | | | |
| 5 | | | | |‘p’ | | |
| 6 |‘p’ |‘p’ |‘p’ |‘p’ | |‘p’ |‘p’ |‘p’
| 7 |‘r’ |‘n’ |‘b’ |‘q’ |‘k’ |‘b’ |‘n’ |‘r’
|=======================================================

Observe que, assim como nos arrays unidimensionais, os índices para linhas
e colunas em matrizes bidimensionais também usam contagem a partir de zero.

Após a transição de arrays unidimensionais para matrizes bidimensionais, é
natural questionar se podem existir matrizes de dimensão ainda maior. Podemos
visualizar uma matriz bidimensional como uma tabela, mas uma
matriz tridimensional é mais difícil de visualizar. No entanto, há
usos para matrizes tridimensionais.

Considere uma professora que está realizando uma pesquisa com os alunos de sua disciplina.
Ela quer saber quantos alunos existem em cada uma das três
categorias: gênero, série e curso. Se ela tratar cada uma delas
como uma dimensão e atribuir um índice a cada valor possível, ela poderia
armazenar os resultados em uma matriz tridimensional. Para gênero, ela poderia
escolher masculino = 0 e feminino = 1. Para ano letivo, ela poderia escolher calouro =
0, segundo ano = 1, terceiro ano = 2, último ano = 3 e outros = 4. Supondo que seja
uma aula de ciência da computação, para área de especialização ela poderia escolher ciência da computação = 0,
matemática = 1, outras ciências = 2, engenharia = 3 e ciências humanas = 4. Usando esse
sistema, ela poderia armazenar de forma compacta o número de alunos em qualquer
combinação de categorias de seu interesse. Por exemplo, o
número total de alunas do segundo ano de engenharia seria armazenado na
célula com índice de gênero 1, índice de série 1 e índice de curso 3.

Três dimensões são geralmente o limite prático ao programar em
Java. Se você encontrar um motivo especialmente bom para usar quatro ou mais
dimensões, fique à vontade para fazê-lo, mas isso deve ocorrer com pouca frequência. A
linguagem Java não tem limite definido para as dimensões de matrizes, mas a maioria das máquinas virtuais
tem a limitação absurdamente alta de 255 dimensões diferentes.

=== Sintaxe: Matrizes avançadas em Java

Agora que discutimos a importância de armazenar dados em listas
multidimensionais, descreveremos os recursos da linguagem Java que permitem
fazer isso. As alterações necessárias para passar de matrizes unidimensionais para
matrizes bidimensionais e de dimensões superiores são simples. Primeiro, vamos
descrever como declarar, instanciar e acessar por índice matrizes bidimensionais
. Em seguida, discutiremos algumas das maneiras pelas quais as matrizes (tanto 
unidimensionais quanto de dimensões superiores) diferem dos tipos de dados primitivos.
Depois, explicaremos como é possível criar matrizes bidimensionais
em Java nas quais as linhas não têm todas o mesmo comprimento. Por fim,
abordaremos alguns dos erros mais comuns que os programadores cometem com
matrizes.

==== Matrizes multidimensionais

Ao declarar uma matriz bidimensional, a principal diferença em relação a um
vetor unidimensional é um par extra de colchetes. Se quisermos
declarar uma matriz bidimensional do tipo `int` na qual possamos armazenar
valores como a tabela de distâncias acima, faríamos o seguinte.

[source,java]
----
int[][] distances;
----

Assim como nos vetores unidimensionais, é válido colocar os colchetes do
outro lado do identificador da variável ou, ainda mais estranho, ter um
par de cada lado.

Depois que a matriz é declarada, ela ainda precisa ser instanciada usando a
palavra-chave `new` antes de poder ser usada. Desta vez, usaremos dois pares de
colchetes, com o número no primeiro par especificando o número de
linhas e o número no segundo par especificando o número de colunas.

[source,java]
----
distances = new int[5][5];
----

Após a instanciação, teremos 5 linhas e 5 colunas, resultando em um
total de 25 posições onde valores `int` podem ser armazenados. A indexação dessas
posições é feita especificando-se os valores de linha e coluna entre os colchetes.
Portanto, para preencher a tabela com as distâncias entre as cidades indicadas acima
, podemos usar o seguinte código tedioso.

[source,java]
----
// Nova York
distances[0][1] = 2791;
distances[0][2] = 791;
distances[0][3] = 1632;
distances[0][4] = 2457;
// Los Angeles
distances[1][0] = 2791;
distances[1][2] = 2015;
distances[1][3] = 1546;
distances[1][4] = 373;
// Chicago
distances[2][0] = 791;
distâncias[2][1] = 2015;
distâncias[2][3] = 1801;
distâncias[1][4] = 1181;
// Houston
distâncias[3][0] = 1632;
distâncias[3][1] = 1546;
distances[3][2] = 1801;
distances[3][4] = 1176;
// Phoenix
distances[4][0] = 2457;
distances[4][1] = 373;
distances[4][2] = 1181;
distances[4][3] = 1176;
----

Você notará que não especificamos valores para `distances[0][0]`,
`distances[1][1]`, `distances[2][2]`, `distances[3][3]` ou
`distances[4][4]`, já que cada um deles já possui o valor padrão de
`0`.

Com muito mais frequência, a manipulação de matrizes multidimensionais usará laços
`for` aninhados. Por exemplo, poderíamos criar uma matriz com 3 linhas e 4
colunas e, em seguida, atribuir valores a esses locais de forma que fossem
numerados em ordem crescente em cada linha.

[source,java]
----
int[][] values = new int[3][4];
int number = 1;
for (int i = 0; i < values.length; ++i) {
    for (int j = 0; j < values[i].length; ++j) {
        values[i][j] = number;
        ++number;
    }
}
----

Este código resultaria em uma matriz preenchida como na tabela a seguir.

[.center%autowidth%unbreakable,cols="4*^",]
|=============
|1 |2 |3 |4
|5 |6 |7 |8
|9 |10 |11 |12
|=============

Os limites do laço `for` externo neste exemplo usam
`values.length`, fornecendo o número total de linhas. Em seguida, o laço `for`
interno usa `values[i].length`, que é o comprimento (número de colunas)
da linha atual. Neste caso, todas as linhas da matriz têm o mesmo
número de colunas, mas isso nem sempre é verdade, como discutiremos
mais adiante.

==== Tipos de referência

Todas as variáveis de matriz são variáveis do tipo _referência_, e não valores simples
como a maioria dos tipos que discutimos até agora. Uma variável de referência é
um nome para um objeto. Você deve se lembrar que descrevemos a diferença
entre tipos de referência e tipos primitivos em
<<Conceitos: Tipos>>, mas o único tipo de referência que
consideramos em detalhes é `String`.

Mais de uma variável de referência pode apontar para o mesmo objeto. Quando um
objeto tem mais de um nome, isso é chamado de _aliasing_. O tipo `String`
é imutável, o que significa que um objeto do tipo `String` não pode mudar
seu conteúdo. As matrizes, no entanto, são _mutáveis_, o que significa que o aliasing
pode causar resultados inesperados. Aqui está um exemplo simples com
aliasing de matriz unidimensional.

[source,java]
----
int[] array1 = new int[10];
for (int i = 0; i < array1.length; ++i) {
    array1[i] = i;
}
int[] array2 = array1;
array2[3] = 17;
System.out.println(array1[3]);
----

Surpreendentemente, o valor impresso será `17`. As variáveis `array1`
e `array2` são referências à mesma matriz fundamental. Ao contrário dos
valores primitivos, o conteúdo completo de `array1` *não* é copiado para
`array2`. Existe apenas uma matriz porque apenas uma matriz foi criada
pela palavra-chave `new`. Quando o índice 3 de `array2` é atualizado, o índice 3
de `array1` também muda, porque as duas variáveis são simplesmente dois
nomes para o mesmo array.

[.text-center]
.Duas referências de array apontando para um único objeto de array.
image::array3.svg[scaledwidth=75%,pdfwidth=75%,width=75%,align="center"]


Às vezes, esse recurso de referência do Java nos permite escrever código que é
confuso ou tem consequências inesperadas. No entanto, a vantagem é que
podemos atribuir uma matriz a outra sem incorrer no custo de
copiar a matriz inteira. Se você criar uma matriz com 1.000.000
elementos, copiar essa matriz várias vezes pode se tornar dispendioso em
termos de tempo de execução do programa.

A melhor regra prática para entender tipos de referência é que
existe apenas um objeto real para cada chamada para `new`. A principal exceção
a essa regra é que os usos de `new` podem ficar ocultos do usuário quando
estão em chamadas de método.

[source,java]
----
String greeting = new String("Hello");
String pronoun = greeting.substring(0,2);
----

No final deste código, a referência `pronoun` apontará para um objeto
contendo a `String "He"`. O método `substring()` invoca `new`
internamente, gerando um novo objeto `String` completamente separado da
`String` referenciada por `greeting`. Este código pode parecer incomum
porque estamos usando explicitamente `new` para criar um objeto `String`
contendo `"Hello"`. A classe `String` é diferente de todas as outras
classes porque pode ser instanciada sem usar a palavra-chave `new`.
A linha `String greeting = "Hello";` chama implicitamente `new` para criar um objeto
contendo a `String "Hello"` e funciona quase da mesma forma que a
linha semelhante acima.

==== Matrizes irregulares

É com vergonha que admitimos que mentimos para vocês. Em Java, não existe
algo como uma verdadeira matriz multidimensional! Em vez disso, os exemplos de
matrizes bidimensionais e tridimensionais que apresentamos acima são,
na verdade, matrizes de matrizes (de matrizes). Pensar em matrizes multidimensionais
dessa forma pode dar ao programador mais flexibilidade.

Se voltarmos à definição da matriz bidimensional com 3 linhas
e 4 colunas, podemos instanciar cada linha separadamente, em vez de como um
bloco.

[source,java]
----
int[][] valores = new int[3][];
int número = 1;
for (int i = 0; i < valores.length; ++i) {
    valores[i] = new int[4];
    for (int j = 0; j < valores[i].length; ++j) {
        valores[i][j] = número;
        ++número;
    }
}
----

Este código é funcionalmente equivalente ao código anterior que
instanciava todas as 12 posições de uma só vez. O mesmo poderia ser feito com uma
matriz tridimensional ou de dimensão superior. Podemos especificar o comprimento de cada linha
independentemente e, o que é mais curioso, podemos atribuir a cada linha um
comprimento diferente. Uma matriz multidimensional cujas linhas têm comprimentos diferentes é
chamada de _matriz irregular_.

Uma matriz irregular geralmente é desnecessária. A principal razão para usar uma matriz irregular
é economizar espaço, quando você tem dados tabulares nos quais os comprimentos
de cada linha variam muito. Se os comprimentos das linhas variam apenas um
pouco, provavelmente não vale a pena o trabalho extra. No entanto, se algumas linhas
têm 10 elementos e outras têm 1.000.000, a economia de espaço pode ser
significativa.

Podemos aplicar a ideia de matrizes irregulares à tabela de distâncias entre
cidades. Se você examinar esta tabela, perceberá que cerca de metade dos
dados nela contidos se repetem, porque a distância de Chicago a Los Angeles
é a mesma que a distância de Los Angeles a Chicago, e assim por diante. Podemos
armazenar os dados em uma forma triangular para manter apenas as informações de distância únicas
.

[.center%autowidth%unbreakable,cols="^.^h,5*^.^",]
|============================
| | Nova York | Los Angeles | Chicago | Houston | Phoenix

| Nova York |0 4+|
| Los Angeles |2.791 |0 3+|
| Chicago |791 |2.015 |0 2+|
| Houston |1.632 |1.546 |1.801 |0 |
| Phoenix |2.457 |373 |1.181 |1.176 |0
|============================

Podemos criar essa tabela em código fazendo o seguinte.

[source,java]
----
distances = new int[5][];
// Nova York
distances[0] = new int[1];
// Los Angeles
distances[1] = new int[2];
distances[1][0] = 2791;
// Chicago
distances[2] = new int[3];
distances[2][0] = 791;
distances[2][1] = 2015;
// Houston
distances[3] = new int[4];
distances[3][0] = 1632;
distances[3][1] = 1546;
distances[3][2] = 1801;
// Phoenix
distances[4] = new int[5];
distances[4][0] = 2457;
distances[4][1] = 373;
distances[4][2] = 1181;
distances[4][3] = 1176;
----

Com esta tabela, um usuário não pode simplesmente digitar `distances[0][4]` e esperar
obter a distância de Nova York a Phoenix. Em vez disso, precisamos ter
cuidado para garantir que o índice da primeira cidade nunca seja maior
do que o índice da segunda cidade. Se estivermos lendo os índices das
cidades fornecidos por um usuário, podemos escrever um código para fazer essa verificação. Digamos que
`city1` e `city2`, respectivamente, conterem os índices das cidades que o
usuário deseja usar para calcular as distâncias entre elas.

[source,java]
----
if (city1 > city2) {
    int temp = city1;
    city1 = city2;
    city2 = temp;
}
System.out.println("A distância é: " + distances[city1][city2] +
    " milhas");
----

Se quiséssemos ser ainda mais espertos, poderíamos eliminar as entradas nulas
da tabela, mas então a matriz irregular teria uma linha a menos do que
a matriz bidimensional original.

==== Armadilhas comuns

Mesmo as matrizes unidimensionais podem dar origem a muitos erros novos. Abaixo, listamos
dois dos erros mais comuns cometidos tanto com matrizes unidimensionais quanto
com matrizes multidimensionais.

.Armadilha: Indicação fora dos limites da matriz
[WARNING]
====

O comprimento de uma matriz é determinado em tempo de execução. Às vezes, o número é
especificado no código-fonte, mas é sempre possível que uma matriz
seja instanciada com base na entrada do usuário. O compilador Java não faz nenhuma
verificação para ver se você está no intervalo correto. Se o seu programa tentar
acessar um elemento inválido, ele irá travar com uma
`ArrayIndexOutOfBoundsException`.

[source,java]
----
int[] array = new int[100];
for (int i = 0; i <= array.length; ++i) {
    array[i] = i;
}
----

Aqui está um exemplo clássico. Ao iterar pelo laço uma vez a mais
, o programa tentará armazenar `100` em `array[100]`, quando o
último índice da matriz é `99`. Em C e {cpp}, a aritmética de ponteiros
permitia que um índice negativo fosse válido para uma matriz em alguns casos. Em
Java, um índice negativo sempre lançará uma
`ArrayIndexOutOfBoundsException`.

Existem outras causas menos comuns para sair dos limites da matriz.
Imagine que você está lendo um arquivo que foi redirecionado para
entrada, mantendo uma contagem das ocorrências de cada letra do alfabeto
no arquivo.

[source,java]
----
Scanner in = new Scanner(System.in);
int[] counts = new int[26];
String palavra;
while (in.hasNext()) {
    palavra = in.next().toLowerCase();
    for (int i = 0; i < palavra.length(); ++i) {
        ++contas[palavra.charAt(i) - 'a'];
    }
}
----

Este trecho de código faz um bom trabalho ao contar as ocorrências de
cada letra. O laço `while` continua a ser executado enquanto houver
outra `String` de dados para ler no arquivo. O laço `for` interno
itera por cada `char` na `String` e incrementa o
elemento apropriado da matriz `counts`. Ao subtrair o valor
`'a'`, normalizamos os valores `char` de `'a'` a `'z'` para `0` a
`25`. No entanto, se houver qualquer sinal de pontuação no arquivo, simplesmente
subtrair `'a'` não funcionará. O valor Unicode de `'.'`, por
exemplo, é 46. O valor Unicode de `'a'` é 97. Subtrair 97 de 46
fará com que este código tente incrementar o índice `-51` da matriz. Uma
verificação adicional deve ser incluída neste código para garantir que o
valor `char` que está sendo examinado seja uma letra.

====

.Armadilha: Matrizes de referência não inicializadas
[AVISO]
====

Outro problema surge apenas com matrizes de tipos de referência. Sempre que
os elementos de uma matriz são tipos de dados primitivos, a memória para esse tipo
é alocada. Sempre que os elementos da matriz são tipos de referência,
apenas referências a objetos, inicializadas como `null`, são alocadas. Como
é uma matriz de valores primitivos, o código a seguir funciona corretamente.

[source,java]
----
int[] primitives = new int[100];
++primitives[67];
----

O código a seguir, no entanto, causará uma `NullPointerException`.

[source,java]
----
String[] references = new String[100];
int x = references[67].length();
----

Matrizes de tipos de referência devem inicializar cada elemento antes de usá-lo.
A `NullPointerException` poderia ser evitada da seguinte forma.

[source,java]
----
String[] references = new String[100];
for (int i = 0; i < references.length; ++i) {
    references[i] = new String();
}
int x = references[67].length();
----

Nesse caso, não haveria erro, embora
`references[67].length()` ainda fosse `0`, e isso provavelmente não é
o que o programador pretendia.

Um erro semelhante pode ocorrer com matrizes multidimensionais.

[fonte,java]
----
int[][] table = new int[10][];
for (int i = 0; i < table.length; ++i) {
    table[i][i] = i;
}
----

Como uma matriz é, por si só, um tipo de referência, a matriz `table` contém
`10` referências a `null` para cada uma de suas `10` linhas. A menos que essas linhas
sejam instanciadas, a JVM lançará novamente uma `NullPointerException` ao
tentar acessar um valor `int` na tabela. Esse erro confunde
muitos programadores iniciantes porque nenhum tipo de referência parece estar
envolvido.

====

=== Exemplos: Matrizes bidimensionais

A seguir, apresentamos alguns exemplos em que as matrizes bidimensionais podem ser úteis.
Começamos com um exemplo simples de calendário, passamos para a multiplicação de matrizes e
vetores, útil em matemática, e terminamos com um jogo.

.Calendário
====

Vamos criar um calendário que possa ser exibido no terminal para
mostrar em que dia da semana cada data cai. Nosso programa solicitará
ao usuário o dia da semana em que o mês começa e o total
de dias do mês. Nosso programa imprimirá rótulos para os
sete dias da semana, seguidos de uma numeração começando no
lugar apropriado, e com quebra de linha de forma que cada dia numerado do mês
caia sob o dia da semana apropriado.

.Imprime um calendário para um determinado mês, formatado semana a semana.
[source, java]
[[CalendarProgram]]
----
include::{programsdir}/Calendar.java[]
----
<1> Primeiro, nosso código cria uma matriz 7 × 7 do tipo
`String` chamado `squares`. A matriz precisa de 7 linhas para que possa começar
com uma linha para rotular os dias e, em seguida, gerar até 6 linhas para cobrir as
semanas. (Meses com 31 dias abrangem partes de 6 semanas diferentes se
começarem em uma sexta-feira ou um sábado.) O número de colunas corresponde aos
sete dias da semana.
<2> Em seguida, inicializamos a primeira linha da
matriz com as abreviações de cada dia da semana.
<3> Depois, inicializamos o
resto da matriz com um único espaço.
<4> Nosso programa então solicita ao usuário o dia em que o mês começa.
<5> O programa também solicita ao usuário o número total de
dias do mês.
<6> O trabalho principal do programa é feito pelo laço `while`, que preenche
cada quadrado com um número de dia que aumenta progressivamente para cada coluna,
passando para a próxima linha quando uma linha é preenchida.
<7> Finalmente, os dois laços `for` aninhados no final imprimem o conteúdo de `squares`, colocando uma
tabulação (`'\t'`) entre cada coluna e iniciando uma nova linha para cada linha.

====

.Multiplicação de matriz por vetor
====

As matrizes oferecem uma maneira natural de representar vetores e matrizes. Em
gráficos 3D e no design de videogames, podemos representar um ponto no espaço 3D como
um vetor com três elementos: _x_, _y_ e
_z_. Se quisermos girar o ponto tridimensional
representado por esse vetor, podemos multiplicá-lo por uma matriz. Por exemplo,
para girar um ponto em torno do eixo _x_ em
_θ_ graus, poderíamos usar a seguinte matriz.

//[stem]
//++++
//\begin{bmatrix}
//1 & 0 & 0 \\
//0 & \cos \theta & -\sin \theta \\
//0 & \sin \theta & \cos \theta \\
//\end{bmatrix}
//++++

[.text-center]
image::matrix.svg[scaledwidth=20%,pdfwidth=20%,width=20%,align="center"]


Dada uma matriz _m_ × _n_ _A_, seja
_A~ij~_ seja o elemento na _i_^-ésima^ linha,
_j_^-ésima^ coluna. Dado um vetor _v_ de comprimento
_n_, seja _v~i~_ o _i_^-ésimo^
elemento do vetor. Para multiplicar _A_ por _v_,
usamos a seguinte equação para encontrar o _i_^-ésimo^ elemento do
vetor resultante _v′_.

//[stem]
//++++
//v'_i = \sum_{j = 1}^n A_{ij}\cdot v_j
//++++

[.text-center]
image::vector.svg[scaledwidth=20%,pdfwidth=20%,width=20%,align="center"]


Ao transformar essa equação em código Java, podemos escrever um programa que
leia um ponto tridimensional e o gire em torno do
eixo _x_ na quantidade especificada pelo usuário.

.Utiliza multiplicação de matrizes para girar um ponto no espaço tridimensional.
[source, java]
[[MatrixRotateProgram]]
----
include::{programsdir}/MatrixRotate.java[]
----
<1> Este programa começa declarando uma matriz do tipo `double` para armazenar o
vetor.
<2> Em seguida, ele lê três valores fornecidos pelo usuário e os insere nela.
<3> Depois, o programa lê o ângulo de rotação em graus e o converte para
radianos.
<4> Em seguida, usamos a classe `Math` para calcular os valores na
matriz de rotação. Observe que não alteramos os valores que precisam ser
zero.
<5> Usamos um laço `for` para realizar a multiplicação matriz-vetor
. Novamente, a soma realizada por
nossos cálculos utiliza o fato de que todos os elementos de `rotatedPoint` são
inicializados como `0.0`.
<6> Finalmente, imprimimos a resposta.
====

[[ticTacToeExample]]
.Jogo da Velha
====

Quase todas as crianças conhecem o jogo da velha, também conhecido como jogo dos três em linha.
A área de jogo é uma grade de 3 × 3. Os jogadores se revezam colocando Xs e Os,
tentando formar uma linha de três. Estrategicamente, não é o jogo mais
interessante, já que dois jogadores que não cometem erros sempre empatam.
Ainda assim, apresentamos um programa que permite que dois jogadores humanos joguem o
jogo, pois as manipulações de uma matriz bidimensional no programa
são semelhantes às de jogos mais complicados, como Connect Four,
damas, xadrez ou Go. Nosso programa detectará qualquer tentativa de jogar em um
lugar que já tenha sido jogado e determinará o vencedor, se
houver um.

Os jogos frequentemente dão origem a programas complexos, já que regras que são
intuitivamente óbvias para os humanos podem ser difíceis de expressar explicitamente em
Java. Nosso programa começa definindo várias variáveis e
objetos.

[source, java]
----
include::{programsdir}/TicTacToe.java[lines=1..15]
----
<.> Primeiro, criamos um `Scanner` para ler os dados.
<.> Em seguida, declaramos
e instanciamos nosso tabuleiro de jogo 3 × 3 como uma
matriz bidimensional do tipo `char`.
<.> Queremos que qualquer espaço não jogado na
grade seja o `char` correspondente a um espaço, então preenchemos a matriz com `' '`.
<.> Em seguida, declaramos um valor `boolean` para controlar de quem é a vez e
outro para controlar se o jogo terminou.
<.> Por fim,
declaramos variáveis para armazenar a linha, a coluna, o número de jogadas
feitas até o momento e a forma atual (`'X'` ou `'O'`).

O núcleo do jogo é um laço `while` que é executado até que `gameOver`
se torne `true`. A primeira linha do corpo desse laço é um atalho
obscuro de Java, frequentemente chamado de _operador ternário_. Essa linha é
na verdade uma abreviação do seguinte.

[source,java]
----
if (turn) {
    shape = 'X';
} else {
    shape = '0';
}
----

O operador ternário funciona com uma condição seguida por um ponto de interrogação
e, em seguida, dois valores separados por dois pontos. Se a condição for `true`,
o primeiro valor é atribuído; caso contrário, o segundo valor é atribuído.
É perfeito para situações como esta, em que um valor é necessário quando
`turn` é `true` e outro é necessário quando `turn` é `false`. O
operador ternário é um truque útil, mas não deve ser usado em excesso.

[source, java]
----
include::{programsdir}/TicTacToe.java[lines=17..37]
----
<.> Após atribuir o valor apropriado a `shape`, nosso código lê os
valores de linha e coluna para o próximo movimento do jogador atual.
<.> Se a linha e a
coluna selecionadas corresponderem a um ponto que já foi ocupado, o
programa exibe uma mensagem de erro.
<.> Caso contrário, o programa define
`board[row][column]` com o símbolo apropriado, incrementa `moves` e
altera o valor de `turn`.
<.> Em seguida, ele exibe o tabuleiro.

Nosso programa não realiza nenhuma verificação de limites em `row` e `column`.
Se um usuário tentar fazer uma jogada na linha 5, coluna 3, nosso programa tentará
fazê-lo e travará. Cláusulas adicionais na instrução `if` poderiam
ser usadas para adicionar verificações de limites.

Talvez a parte mais complicada do nosso programa de jogo da velha seja verificar se há uma
vitória.

[source, java]
----
include::{programsdir}/TicTacToe.java[lines=38..70]
----
<.> Primeiro, verificamos cada linha para ver se ela contém três em sequência.
<.> Em seguida, verificamos cada coluna.
<.> Por fim, verificamos as duas diagonais.
<.> Se qualquer uma
dessas verificações encerrar o jogo, anunciamos um vencedor.
<.> Caso contrário, se o
número de jogadas atingir 9 sem um vencedor, deve ser um empate.

Em
um jogo maior (como o Connect Four), gostaríamos de encontrar maneiras melhores
de automatizar a verificação de linhas, colunas e diagonais. Por exemplo, não
gostaríamos de verificar todo o tabuleiro a cada jogada.
Em vez disso, poderíamos nos concentrar apenas nas linhas, colunas e diagonais
afetadas pela última jogada.
====

****
<<connectFourExercise>>
****

=== Avançado: Ferramentas especiais para matrizes em Java

As matrizes são estruturas de dados fundamentais em muitas linguagens de programação.
Frequentemente, existem ferramentas sintáticas especiais ou bibliotecas projetadas para
facilitar seu uso. Nesta seção, exploramos duas ferramentas avançadas: o
laço `for` aprimorado e a classe utilitária `Arrays`.


==== Laços `for` aprimorados

Em <<repetition#repetition>>, descrevemos três laços: o laço `while`
, o laço `for` e o laço `do`-`while`. Embora esses sejam os únicos
três laços em Java, existe uma forma especial do laço `for` projetada
para uso com matrizes (e algumas outras estruturas de dados). Essa construção é
frequentemente chamada de _laço `for` aprimorado_.

Um laço `for` aprimorado não possui o cabeçalho de três partes de um laço `for`
normal. Em vez disso, ele foi projetado para iterar sobre o conteúdo de uma matriz ou outra lista.
Dentro de seus parênteses há uma declaração de uma variável com o mesmo tipo
que os elementos da matriz, seguida de dois pontos (`:`), e então o nome da
matriz. Considere o exemplo a seguir de um laço `for` aprimorado usado para somar os
valores de uma matriz de valores `int` chamada `array`. Assim como em todos os laços em
Java, as chaves são opcionais se houver apenas uma instrução executável no
laço.

[source,java]
----
int sum = 0;
for (int value : array) {
    sum += value;
}
----

Este código funciona exatamente da mesma maneira que o laço `for`
tradicional que usaríamos para resolver o mesmo problema.

[source,java]
----
int sum = 0;
for (int i = 0; i < array.length; ++i) {
    sum += array[i];
}
----

A vantagem do laço `for` aprimorado é que ele é mais curto e mais claro.
Também não há preocupação com erros de deslocamento de um índice. O
laço `for` aprimorado itera sobre todos os elementos da matriz, sem necessidade de
índices!

Os laços `for` aprimorados podem ser aninhados ou usados dentro de outros laços. Considere os
seguintes laços `for` aprimorados aninhados que imprimem todas as peças de xadrez
possíveis, nas cores preta e branca.

[source,java]
----
String[] cores = {"Preto", "Branco"};
String[] peças = {"Rei", "Rainha", "Torre", "Bispo", "Cavalo", 'Peão'};
for (String cor : cores) {
    for (String peça : peças) {
        System.out.println(cor + " " + peça);
    }
}
----

Os laços `for` aprimorados têm algumas desvantagens. Por um lado, eles foram projetados para iterar
por uma matriz inteira. É complicado tentar fazê-los parar mais cedo, e
é impossível fazê-los voltar a valores anteriores. Eles também
foram projetados apenas para acesso de *leitura*, não para acesso de gravação. A variável no
cabeçalho do laço `for` aprimorado assume cada valor da matriz por vez,
mas atribuir valores a essa variável *não tem efeito* sobre a
matriz subjacente. Considere o seguinte laço `for` que atribui `5` a todos os valores
em `array`.

[source,java]
----
for (int i = 0; i < array.length; ++i) {
    
array[i] = 5;
}
----

Esse tipo de atribuição é impossível em um laço `for` aprimorado. O
laço `for` aprimorado "equivalente" não faz nada. Ele atribui `5` à variável local
`value`, mas nunca altera o conteúdo de `array`.

[source,java]
----
for (int value : array) {
    
value = 5;
}
----

Embora os laços `for` aprimorados sejam ótimos para matrizes, eles também podem ser usados para
qualquer estrutura de dados que implemente a interface `Iterable`. Nós
discutimos interfaces em <<interfaces#interfaces>> e estruturas de dados dinâmicas
em <<dynamic-data-structures#dynamic-data-structures>> e
<<recursion#recursion>>.

==== A classe `Arrays`

Os criadores da API Java sabiam que as matrizes eram importantes e adicionaram
uma classe especial `Arrays` para manipulá-las.

Essa classe possui vários métodos estáticos que podem ser usados para procurar
valores em matrizes, criar cópias de matrizes, copiar intervalos selecionados de matrizes,
verificar se matrizes são iguais, preencher matrizes com valores específicos, ordenar matrizes,
converter uma matriz inteira em uma representação `String` e muito mais. As
assinaturas dos métodos abaixo são fornecidas para matrizes `double`, mas a maioria
dos métodos é sobrecarregada para funcionar com todos os tipos primitivos e de referência
.

[.center%unbreakable,width=100%,cols="<.<55%l,<.<45%"]
|=======================================================================
|Método |Finalidade

|binarySearch(double[] array, double value) |Retorna o índice de `value`
dentro de `array` ou um número negativo se ele não for encontrado. Somar 1 ao
número negativo e, em seguida, negá-lo resultará no índice onde o
valor estaria. Observação: `array` deve estar ordenado para que este método funcione.

|copyOf(double[] array, int length) |Retorna uma cópia de `array` com
comprimento `length`, truncada ou preenchida se não corresponder ao
comprimento de `array`.

|copyOfRange(double[] array, int from, int to) |Retorna uma cópia de
`array` do intervalo que começa em `from` e vai até, mas não
inclui, `to`.

|equals(double[] array1, double[] array2) |Retorna `true` se `array1`
e `array2` tiverem o mesmo número de elementos, sendo que cada par deles é
igual.

|fill(double[] array, double value) |Preenche `array` com cópias de
`value`.

|sort(double[] array) |Classifica `array` usando a ordenação natural. Este
método pode falhar para matrizes `Object` nas quais os objetos não são
comparáveis.

|toString(double[] a) |Retorna uma `String` contendo representações
de cada elemento separadas por vírgulas.
|=======================================================================

Consulte a API para obter mais informações. Embora tarefas como `fill()`
sejam simples, vale a pena usar o método de `Arrays` em vez de
escrever o seu próprio. Os métodos na API Java geralmente foram otimizados para
velocidade e usam instruções especiais que não estão acessíveis a programadores Java
comuns.

=== Solução: Jogo da Vida

Aqui apresentamos nossa solução para a simulação do Jogo da Vida de Conway.
Nosso programa foi projetado para executar a simulação com 24 linhas e 80
colunas, embora seja fácil alterar essas dimensões.

[source, java]
----
include::{programsdir}/Life.java[lines=1..13]
----
<.> O método `main()` do nosso programa começa definindo `ROWS`, `COLUMNS`
e `GENERATIONS` como constantes nomeadas usando a palavra-chave `final`.
<.> Em seguida,
criamos *duas* matrizes com `ROWS` linhas e `COLUMNS` colunas. A matriz `board`
armazenará a geração atual. A matriz `temp` será usada para
preencher a próxima geração. Em seguida, `temp` será copiado para `board`,
e o processo se repetirá. A variável `swap` é apenas uma referência que usaremos
para trocar `board` e `temp`.
<.> Preenchemos o tabuleiro aleatoriamente, tornando
10% das células vivas. Novamente, você pode querer brincar com esse número para
ver como os padrões na simulação são afetados.

[source, java]
----
include::{programsdir}/Life.java[lines=14..36]
----
<.> O laço `for` no início deste segmento de código é executado uma vez para
cada geração que simulamos.
<.> Os dois laços `for` aninhados examinam cada
célula em `board`.
<.> Os dois laços `for` aninhados dentro desses laços realizam os
cálculos para determinar se uma célula estará viva ou morta na próxima
geração. Esses laços internos começam uma linha antes da linha atual e
terminam uma linha depois da linha atual. Eles fazem o mesmo para as colunas. Os
métodos `Math.max()` e `Math.min()` são usados para impedir que os laços
saíam dos limites da matriz. Ao retroceder uma linha ou uma coluna, os métodos 
`Math.max()` garantem que não geremos um índice menor
que 0. Ao avançar uma linha ou uma coluna, os métodos `Math.min()`
garantem que não geremos um índice maior que `ROWS - 1` ou
`COLUMNS - 1`.
<.> Depois que esses dois laços `for` mais internos contam o total de células vivas
ao redor da célula em questão, decidimos o destino da célula para
a próxima geração. Se a célula estiver viva e tiver exatamente 2 ou 3 vizinhos vivos
, ela continuará viva.
<.> Se uma célula estiver morta, ela
voltará à vida somente se tiver exatamente 3 vizinhos vivos.
<.> Depois de
armazenarmos o estado de cada célula na próxima geração em `temp`,
trocamos `board` e `temp`, usando a variável `swap`. Poderíamos ter descartado
a matriz antiga armazenada em `board` em vez de trocá-la com `temp`,
mas então teríamos que criar uma nova matriz para `temp` a cada vez, o que
é menos eficiente.

[source, java]
----
include::{programsdir}/Life.java[lines=37..54]
----
<.> O primeiro laço `for` neste segmento imprime 100 linhas em branco para limpar a
tela, como explicamos anteriormente.
<.> Os dois laços `for` aninhados imprimem
o estado da geração atual, com um `*` para cada célula viva e
um espaço em branco para cada célula morta.
<.> Após a saída, o código fica em espera por
500 milissegundos para dar o efeito de uma animação. Discutiremos
exceções em geral em <<exceptions#exceptions>> e daremos mais
informações sobre o método `Thread.sleep()` em <<concurrency#concurrency>>.

Embora 500 milissegundos
(meio segundo) seja um longo atraso para uma animação, o efeito de rolagem da tela
torna o padrão de células vivas e mortas difícil de perceber em um terminal.
Algum tipo de GUI (como discutimos em <<gui#gui>>) poderia oferecer
uma maneira mais agradável de visualizar o Jogo da Vida, mas desenhar padrões arbitrários
em uma GUI apresenta suas próprias dificuldades.

****
<<lifeGUIExercise>>
****

=== Concorrência: Matrizes

As matrizes são fundamentais para a programação concorrente em Java. Em
<<concurrency#concurrency>>, explicaremos como
criar threads de execução independentes, cada uma delas vinculada a um
objeto `Thread`. Se você tiver um computador com dois, quatro ou mais núcleos,
talvez queira usar duas ou quatro threads para resolver um problema, mas alguns
programas podem usar centenas. Como você pode acompanhar todos esses objetos `Thread`
? Em muitos casos, você manterá referências a eles em uma matriz.

As matrizes também podem conter grandes listas de dados. É comum que programas com threads
compartilhem uma única matriz na qual cada thread lê e grava. Dessa
forma, os custos de memória são mantidos baixos, pois há apenas uma cópia de todos os
dados. No caso mais simples, cada thread trabalha em alguma parte da
matriz sem interagir com o restante. Mesmo assim, como você atribui
partes da matriz às diferentes threads?

Vamos supor que cada elemento da matriz precise ser processado de
alguma forma. Por exemplo, podemos querer registrar se cada
`long` em uma matriz é primo ou não. Se você tiver _k_ threads
e uma matriz de comprimento _n_, onde _n_ é
um múltiplo de _k_, então é fácil: cada thread recebe
exatamente _n_/_k_ itens para trabalhar. Por exemplo, a primeira
thread trabalhará nos índices de 0 a _n_/_k_ - 1, a
segunda thread trabalhará nos índices de _n_/_k_ a
2__n__/_k_ - 1, e assim por diante, com a última thread trabalhando
nos índices de (_k_
- 1)_n_/_k_ a _n_ - 1. Nem todos os elementos da matriz
exigirão a mesma quantidade de computação, mas frequentemente assumimos que
sim, pois pode ser difícil adivinhar quais elementos levarão
mais tempo para serem processados.

E se o número de elementos na matriz não for um múltiplo do
número de threads? Ainda assim, queremos distribuir o trabalho da forma mais justa
possível. Programadores iniciantes às vezes se sentem tentados a usar a mesma
aritmética do caso em que as threads dividem igualmente o comprimento
da matriz: cada thread recebe ⌊_n_/_k_⌋ (usando divisão inteira
) elementos, e deixamos a última thread com o que sobrar. Quão
ruim isso pode ser?

****
<<dividingArraysExercise>>
****


Essa distribuição de trabalho pode ficar muito mal equilibrada. Considere um caso
com 10 threads e 28 dados. ⌊28/10⌋ = 2,
usando divisão inteira. Assim, as primeiras nove threads têm 2 unidades de
trabalho a fazer, mas a última thread fica com 10! Isso não é apenas
injusto; é ineficiente. A pessoa que escreve o programa provavelmente quer
minimizar o tempo total necessário para concluir o trabalho. Neste
caso, o tempo desde o início da primeira thread até o término da última
é chamado de _makespan_ da tarefa. Com essa divisão de trabalho,
o makespan é de 10 unidades de trabalho.

[.text-center]
.Unidades de trabalho por thread usando uma estratégia ingênua.
image::split1.svg[scaledwidth=60%,pdfwidth=60%,width=60%,align="center"]


.Atribuição justa do trabalho
====

Uma maneira simples de resolver esse problema é observar o valor
_n_ mod _k_, o resto da divisão de _n_ por
_k_. Queremos distribuir esses restos entre as primeiras threads.
Sabemos que qualquer resto será menor que _k_. Se o
índice da thread (começando em 0, é claro) for menor que o
resto, adicionamos um elemento extra ao seu trabalho. Dessa forma, 28 unidades de
trabalho distribuídas por 10 threads darão 3 elementos às primeiras 8 threads
e 2 elementos às demais. Usando essa estratégia, o tempo de execução total passa a ser de 3
unidades de trabalho, uma grande melhoria em relação a 10. Encontrar uma maneira de distribuir
o trabalho por várias threads para melhorar a eficiência é uma forma de _balanceamento de carga_,
um termo amplo para a divisão do trabalho entre recursos de computação.

[.text-center]
.Unidades de trabalho por thread usando uma estratégia justa.
image::split2.svg[scaledwidth=60%,pdfwidth=60%,width=60%,align="center"]

O programa abaixo lê o comprimento de uma matriz e o número de threads do usuário e, em seguida, imprime a quantidade de trabalho para cada um. Você deve ser capaz de adaptar as ideias contidas nele aos seus próprios programas multithread em <<concurrency#concurrency>>.

.Modelo para atribuir trabalho a threads.
[source, java]
[[AssigningWorkProgram]]
----
include::{programsdir}/AssigningWork.java[]
----

====

=== Exercícios
*Problemas conceituais*

. Por que uma matriz não pode ser usada para armazenar uma lista de comprimento arbitrário de
números inseridos por um usuário? Quais são as estratégias que podem ser utilizadas para
superar esse problema?
. Nos próximos capítulos, apresentaremos uma estrutura de dados chamada
_lista encadeada_. Uma lista encadeada é uma estrutura de dados homogênea e dinâmica
com acesso sequencial (ao contrário de uma matriz, que tem acesso aleatório). Você
pode saltar instantaneamente para qualquer lugar em uma matriz, mas precisa percorrer
cada elemento de uma lista encadeada para chegar ao que deseja, mesmo
que saiba exatamente sua posição na lista. Por outro lado,
a inserção de valores no início de uma lista encadeada pode ser feita em uma
única etapa, enquanto uma matriz precisaria ter seu tamanho redimensionado e seu conteúdo
copiado. Liste algumas tarefas para as quais uma matriz seria melhor do que uma
lista encadeada e vice-versa.
. Dado o seguinte código:
+
[source,java]
----
double[] array1 = new double[50];
double[] array2 = new double[50];
for (int i = 0; i < array1.length; ++i) {
    array1[i] = i + 1;
    array2[i] = array2.length - i;
}
array2 = array1;
for (int i = 1; i < array1.length; ++i) {
    
array1[i] = array1[i - 1] + array1[i];
}
----
+
Qual é o valor em `array2[array2.length - 1]` após a execução deste código
?
. Que erro será causado pelo código a seguir e por quê?
+
[source,java]
----
String[] array = new String[100];
System.out.println(array[99].charAt(0) +
           " é a primeira letra da última String.");
----
. Uma matriz de comprimento _n_ em Java normalmente ocupa
_n_ vezes o número de bytes para cada elemento, mais
16 bytes adicionais de sobrecarga. Como um `int` usa 4 bytes de armazenamento,
uma matriz de 100 elementos `int` ocuparia 416 bytes. Considere a
seguinte declaração e alocação de uma matriz tridimensional.
+
[source,java]
----
int[][][] data = new int[10][5][20];
----
+
Quantos bytes são alocados para esta matriz? Lembre-se de que a 
sobrecarga de 16 bytes ocorrerá repetidamente, já que Java cria uma matriz tridimensional
como uma matriz de matrizes de matrizes.
. Nossa tabela original de distâncias entre cidades aloca
5 · 5 = 25 elementos `int` para armazenar todas as distâncias
entre as cinco cidades, incluindo repetições. Quantos elementos `int` são
alocados para a versão em matriz triangular irregular desta tabela de distâncias entre cidades
? Se usássemos o estilo de tabela normal, _n_ cidades
exigiriam _n_^2^ elementos `int`. Quantos elementos a
versão em matriz triangular irregular alocaria para _n_ cidades?
. [[dividingArraysExercise]] Considere o método ingênuo de dividir
uma matriz de comprimento _n_ entre _k_ threads que
foi discutido em <<Concorrência: Matrizes>>: Cada thread recebe
⌊_n_/_k_⌋ (arredondado para baixo devido à divisão inteira) elementos,
e a última thread recebe os elementos extras. Que expressão matemática
descreve quantos elementos extras são alocados para a última thread? Você consegue
pensar em um exemplo em que o último elemento receba *todos* os
elementos? O que deveria ter acontecido neste caso usando o outro esquema, mais
justo, para atribuir os dados às threads?

*Exercício de Programação*

. [[wordSearchPunctuationExercise]] No <<wordSearchExample>>,
nosso código não consideraria `ship,` como uma ocorrência de `ship` devido à
vírgula.
+
Reescreva o código do <<wordSearchExample>> para remover
sinais de pontuação do início e do fim de uma palavra. Use um laço que seja executado
enquanto o caractere no início de uma palavra não for uma letra,
substituindo a palavra por uma subcadeia dela mesma que não inclua o
primeiro caractere. Use um segundo laço para remover caracteres que não sejam letras do final de
uma palavra. Tome cuidado para parar se o comprimento da `String` se tornar 0, como
no caso de um texto composto inteiramente por caracteres que não sejam letras.
. [[wordBinarySearchExercise]] Em <<wordSearchExample>>, nós
escrevemos um programa que conta as ocorrências de cada palavra de uma lista
dentro de um texto. Se a lista de palavras a ser pesquisada for longa, pode
levar bastante tempo para pesquisar toda a lista. Se a lista de
palavras estivesse ordenada, poderíamos usar um truque que nos permitiria pesquisar
muito mais rápido. Poderíamos jogar um jogo de "`alto-baixo`", pesquisando na
lista verificando a palavra do meio na matriz. Se essa palavra estiver muito
ao final do alfabeto, repita a pesquisa na primeira metade da lista. Se estiver
muito no início do alfabeto, repita a pesquisa na segunda metade da
lista. Ao dividir repetidamente a lista ao meio, até que você encontre
a palavra que está procurando ou restrinja sua busca a uma única
palavra incorreta, você pode pesquisar muito mais rápido. Esse tipo de pesquisa é
chamado de _busca binária_ e usa cerca de log _n_ comparações
para encontrar um elemento em uma lista de _n_ itens. Em contraste, examinar a lista um
elemento de cada vez leva cerca de _n_ comparações.
+
Reescreva o código de <<wordSearchExample>> para usar a
busca binária, após aplicar a ordenação por seleção de <<selectionSortExample>>. Embora a ordenação por seleção leve algum tempo extra, você deve
mais do que compensar a diferença com uma busca tão rápida. Para implementar
a busca binária, mantenha variáveis para o início, meio e fim da
lista. Continue ajustando as três variáveis até que o índice do meio tenha a
palavra que você está procurando ou até que as variáveis de início e fim se encontrem. Lembre-se de
usar o método `compareTo()` da classe `String` para comparar palavras.
. [[modeExercise]] Em <<statisticsExample>>, apresentamos um programa que encontra o
máximo, mínimo, média, desvio padrão e mediana de uma lista de
valores. Outra estatística que às vezes é importante é a _moda_, ou
o elemento que ocorre com mais frequência. Por exemplo, na lista
{1, 2, 3, 3, 3, 5, 6, 6, 10}, a moda é 3. Escreva um
programa que possa determinar a moda de uma determinada lista de valores `int`. Uma
lista pode ter múltiplas modas se mais de um elemento ocorrer com
frequência máxima. Para nossos propósitos, consideraremos que qualquer lista com
múltiplas modas, significa que não tem modas. Você pode querer ordenar a lista antes de
iniciar o processo de contagem da frequência de cada valor.
. [[connectFourExercise]] Usamos o exemplo do jogo da velha em
<<ticTacToeExample>> porque um jogo mais complexo teria
ocupado muito espaço para ser resolvido. O jogo Connect Four (ou
_Captain's Mistress_, como era chamado originalmente) coloca dois jogadores
um contra o outro em um tabuleiro vertical de 6 × 7. Um
jogador usa peças vermelhas, enquanto o outro usa pretas. Os dois jogadores
se revezam colocando suas peças nas colunas do tabuleiro, nas quais
as peças cairão até a linha vazia mais baixa, devido à gravidade. O objetivo
do jogo é ser o primeiro a formar quatro peças da sua cor em uma linha.
+
Implemente uma versão do _Connect Four_ para dois jogadores humanos, semelhante à
nossa versão do jogo da velha. Muitas das ideias são as mesmas,
mas os detalhes são mais complicados. Primeiro, um jogador escolherá apenas uma
coluna específica. Seu programa deve então descobrir em qual linha uma peça
colocada nessa coluna irá cair. Em seguida, o processo de contar
quatro em linha é mais difícil do que os três em linha do jogo da velha.
Você precisará de mais laços para automatizar totalmente o processo.
. [[lifeGUIExercise]] Depois de dominar o material em
<<gui#gui>>, adapte a
solução para o Jogo da Vida de Conway de <<Solução: Jogo da Vida>>
para exibição em uma interface gráfica de usuário. Você pode usar um
`GridLayout` para organizar um grande número de objetos `JLabel` em uma grade e
atualizar suas cores de fundo para `Color.BLACK` e `Color.WHITE` conforme
necessário, usando o método `setBackground()`. (Para tornar essas cores
visíveis, você também precisará chamar o método `setOpaque()` uma vez em
cada `JLabel` com o argumento `true`.) O Jogo da Vida é muito mais
atraente com uma GUI real em vez de uma representação improvisada na linha de comando
.

*Experimentos*

. Criar matrizes com comprimentos cada vez maiores requer mais
tempo de processador, já que todos esses elementos devem ser inicializados com
algum valor padrão. Usando um comando `time` do sistema operacional, determine a quantidade de
tempo que leva para criar uma matriz `int` de comprimento 10, 10.000 e
10.000.000. Muito provavelmente, o tempo que a instanciação da
matriz leva é uma pequena parte do programa, e você deve notar muito
pouca diferença entre esses três tempos. No entanto, o tempo não é o único
recurso importante. Quando você executa uma JVM, ela possui um tamanho de heap padrão que
limita a quantidade de espaço que você pode usar para criar novos objetos, incluindo
matrizes. Quando você exceder esse tamanho, seu programa irá travar com um
`OutOfMemoryError`. Experimente diferentes tamanhos de matrizes até que você
consiga estimar o tamanho do seu heap com uma precisão de cerca de 5 MB.
+
Essa estimativa será muito aproximada, já que a JVM usa outra memória em
segundo plano. Para ter uma ideia mais precisa, você pode usar o
método `Runtime.getRuntime().maxMemory()` para determinar o tamanho máximo de memória da JVM
e o
método `Runtime.getRuntime().totalMemory()` para determinar a memória total da JVM
em uso.
. Execute a implementação do programa de busca de palavras usando o aprimoramento de
busca binária de <<wordBinarySearchExercise>>. Use o comando
`time` para medir a diferença de tempo entre as versões de busca regular e binária
do programa com uma longa lista de palavras. Você pode notar
muito pouca diferença em entradas pequenas, mas pode facilmente encontrar uma lista das
1.000 palavras mais usadas em inglês na Internet, juntamente com
textos longos e livres de direitos autorais em
https://www.gutenberg.org[Projeto Gutenberg^]. Combinar esses dois em uma única entrada
deve resultar em um aumento significativo na velocidade da versão com busca binária
em relação à versão regular.
. Gere arquivos de entrada consistindo em 1.000,
10.000 e 100.000 valores `int` aleatórios.
Cronometre nossa implementação da ordenação por seleção de
<<selectionSortExample>> rodando em cada um desses arquivos de entrada
e redirecionando a saída para arquivos de saída. Qual é o comportamento do
tempo de execução à medida que o comprimento da entrada aumenta em um fator de 10? Como uma
função de _n_, quantas vezes no total o corpo do laço `for` interno
é executado durante a ordenação por seleção? Essa função reflete fielmente
o aumento no tempo de execução?
