[#methods]
:imagesdir: chapters/methods/images
:programsdir: chapters/methods/programs
== Methods

[quote, William Shakespeare]
____
Polônio (em voz baixa): Embora isso seja loucura, há um método nisso.
____

=== Problema: Pôquer de três cartas

O jogo exerce um fascínio sobre a humanidade desde sua invenção. Desde
que existem matemáticos, eles vêm estudando os mecanismos subjacentes
de probabilidade e estatística que regem os jogos de azar. Um
jogo clássico que envolve tanto estatística quanto estratégia é o pôquer. O problema que
queremos resolver é programar uma das muitas variações do pôquer, chamada
pôquer de três cartas. Em vez de blefar, o jogador compete apenas com a
casa, de acordo com regras fixas, sem espaço para psicologia. O jogador
recebe três cartas. Se a mão do jogador contiver um par ou melhor, ele
ou ela ganha um prêmio maior ou igual ao valor apostado. Se o
jogador não tiver um par ou melhor, ele ou ela perde o valor apostado.
Abaixo está uma tabela que apresenta um conjunto possível de prêmios para cada
mão possível.

[.center%autowidth%unbreakable,cols="^,^,^,^,^"]
|===================
|Mão |Casa | |Mão | Casa

|Straight Flush |40| |Flush |2
|Trinca |30| |Par |1
|Sequencia |6| |Nada |0
|===================

Se você não está familiarizado com as regras do pôquer ou com jogos de cartas em geral, aqui vai
uma explicação rápida sobre as várias mãos. Um baralho tradicional inglês ou
americano é composto por 52 cartas, organizadas em quatro
naipes: espadas, copas, ouros e paus. Em cada naipe, há 13
valores: dois, três, quatro, cinco, seis, sete, oito, nove, dez, valete,
rainha, rei e ás.

No pôquer de três cartas, uma sequência ocorre quando as três cartas podem ser organizadas
de forma que seus valores (independentemente do naipe) estejam em ordem. Por exemplo, uma mão
composta por um quatro de ouros, um cinco de espadas e um seis de paus
constituiria uma sequência. Um Ás pode servir tanto como a carta de valor mais alto
(vindo depois do Rei) quanto como a de valor mais baixo (vindo antes do Dois)
e pode ajudar a formar uma sequência em qualquer uma dessas funções (mas não em ambas ao mesmo
tempo). Um flush ocorre quando todas as três cartas têm o mesmo naipe. Por exemplo,
um Três de Copas, um Sete de Copas e um Valete de Copas
constituiriam um _flush_ no pôquer de três cartas. Um _straight flush_, a
mão mais alta, é composto por cartas que formam tanto uma sequência (pela ordem de valor)
quanto um flush (pela uniformidade do naipe). Uma trinca ocorre quando todas as
três cartas têm o mesmo valor, e um par ocorre quando duas das cartas
têm o mesmo valor. Quando nenhuma dessas condições se aplica, a mão não tem
nenhuma designação especial no pôquer de três cartas, e a aposta é perdida.

Sua tarefa é escrever um programa que funcione como uma versão computadorizada do
jogo. Você deve criar um baralho de 52 cartas, embaralhá-las completamente
para simular o embaralhamento e selecionar as três primeiras cartas como uma mão. Você
deve então determinar a classificação mais alta que se aplica à mão de
cartas e os ganhos correspondentes (se houver).

Qualquer solução razoável para este problema utiliza matrizes, discutidas no
capítulo anterior. Usando apenas esse conhecimento, você deve ser capaz de
criar um jogo de pôquer de três cartas. No entanto, o foco deste capítulo são
_métodos_, que podem ser usados para dividir a solução de um problema em
partes lógicas. Ao dividir a solução dessa maneira, seremos capazes de
resolver o problema do pôquer de três cartas de uma forma relativamente curta, elegante e
fácil de ler.

=== Conceitos: Dividindo o trabalho em segmentos

Você deve ter percebido que as soluções para os problemas com os quais temos trabalhado
têm se tornado cada vez mais complexas à medida que o livro avança. Essa
progressão se deve, em parte, ao fato de querermos resolver problemas mais interessantes 
com soluções mais complexas, mas também porque introduzimos ferramentas adicionais do Java 
que tornam possível a resolução desses problemas mais difíceis.

Surpreendentemente, as ferramentas que apresentamos neste capítulo não permitem que você resolva um
problema que não pudesse resolver antes. Em vez disso, as ferramentas deste capítulo
e do próximo tornam a resolução de um problema mais fácil e menos suscetível
a erros. Uma lista relativamente longa e complicada de instruções Java era
necessária para resolver problemas como o programa de estatística ou o Jogo
da Vida de Conway. Em vez de resolver esses problemas como um único
segmento monolítico de código, podemos dividir nossas soluções em unidades chamadas _métodos estáticos_
.

==== Razões para os métodos `static`

Um método estático é um segmento curto e nomeado de código que foi agrupado
de modo a poder ser _chamado_ de outras partes do programa. Sempre que
a tarefa executada por esse método for necessária, a execução do
programa salta para o código do método, realiza o trabalho que deve
fazer e, em seguida, retorna ao que estava fazendo antes.

As razões para usar métodos estáticos podem ser resumidas em três
pontos essenciais:

Modularidade:::
  Pouquíssimos softwares são escritos por uma única pessoa. Softwares comerciais
  podem envolver dezenas ou até centenas de desenvolvedores no
  projeto, na implementação, nos testes e na manutenção do código. Quando o código
  é dividido em métodos individuais, esses métodos podem ser escritos e
  testados por pessoas diferentes com o mínimo de interferência. É muito
  mais difícil trabalhar em conjunto em um único bloco gigante de código.
Legibilidade:::
  Métodos são segmentos de código *nomeados*. Quando um método é chamado, seu
  nome é usado. Se for escolhido um nome significativo, a linha no código
  que chama o método ajuda a documentar o código, explicando o que está
  acontecendo. Por exemplo, se for usado um método chamado `sort()`, um leitor
  compreende instantaneamente que algo está sendo classificado. Se, em vez de um
  método `sort()` separado, o código que realiza a classificação fosse colado
  no mesmo local, um leitor talvez tivesse que dedicar alguns instantes para
  compreender o significado dessas linhas de código, especialmente sem
  comentários.
Reutilização:::
  O fato de um método poder ser chamado de qualquer lugar do código o torna
  reutilizável. Para usar o exemplo `sort()` novamente, talvez tenhamos que classificar
  vários arrays diferentes em um único programa. Sem métodos, teríamos
  que ficar copiando e colando código repetidamente. Com
  métodos, a quantidade total de código-fonte pode ser menor. Na verdade, se
  você se pegar copiando e colando código, isso geralmente é um indício
  de que um método seria útil. +
{empty} +
Essa ideia de reutilização vai além de programas individuais. Um
método estático pode ser chamado a partir de um programa totalmente diferente. Se você
criar um método que seja realmente útil, fica à vontade para usá-lo em outros
programas que escrever. Ao fazer isso, você só precisa fazer alterações em
um único lugar caso descubra erros ou queira ampliar sua
funcionalidade.

==== Paralelismo com funções matemáticas

Temos discutido a utilidade dos métodos estáticos sem explicar
exatamente o que eles são. Uma maneira de compreender melhor os métodos é
reconhecer sua semelhança com as funções da matemática. Em
linguagens procedurais (não orientadas a objetos), como o C, os equivalentes dos
métodos estáticos são geralmente chamados de funções. Assim como
as funções na matemática, um método estático recebe um certo número de entradas
(possivelmente até zero) e, geralmente, produz algum resultado.

Você já utilizou vários métodos estáticos da classe `Math`, como
`Math.sqrt()`. Considere a seguinte função.

//[stem]
//++++
//f(x) = \sqrt{x}
//++++

[.text-center]
image::root.svg[scaledwidth=15%,pdfwidth=15%,width=15%]


Essa função reflete o código dentro de `Math.sqrt()`. Na matemática, quando você aplica _f_(_x_) a 
um valor específico, pode escrever _y_ = _f_(5). Em Java,
você pode digitar o seguinte.

[source,java]
----
double y = Math.sqrt(5);
----

Na expressão _f_(5), a variável placeholder _x_ assume o valor 5.
Da mesma forma, alguma variável dentro de
`Math.sqrt()` assume o valor `5` quando o método é chamado.

É importante compreender essa semelhança entre métodos e
funções matemáticas, pois os criadores de muitas linguagens de programação
foram diretamente influenciados pela notação mais antiga. No entanto,
também existem muitas diferenças entre os dois conceitos.
Funções matemáticas podem receber mais de uma entrada, assim como os métodos Java
. Os métodos Java também podem não receber nenhuma entrada, enquanto a ideia central de uma
função matemática é mapear algum(ns) valor(es) de entrada para algum valor de saída
. Os métodos Java nem sempre têm valores de saída. Eles podem
simplesmente *fazer* algo.

==== Fluxo de controle

Já discutimos instruções de seleção, como `if` e `switch`, bem
como três estruturas de loop diferentes: `for`, `while` e `do`-`while`.
Cada um desses recursos da linguagem Java é usado para o fluxo de controle. As
instruções de seleção permitem que seu programa escolha qual código executar.
Os loops permitem que seu código execute repetidamente determinado trecho de código. Os métodos
também afetam o fluxo de controle. Quando um método é chamado, a execução do
programa salta para dentro do método, realiza todo o trabalho necessário ali e
depois retorna ao código que o chamou. Lembre-se do exemplo muito simples
apresentado acima.

[source,java]
----
double y = Math.sqrt(5);
----

A JVM alocou uma variável do tipo `double` e está se preparando para
atribuir um valor a ela. De repente, a execução da JVM salta para o
código dentro do método `Math.sqrt()`. É necessária uma 
quantidade não trivial de trabalho para calcular a raiz quadrada de um número. Depois que
esse cálculo é concluído, o fluxo de execução retorna à atribuição
que ficou aguardando todo esse tempo. Assim como uma função matemática,
podemos tratar a chamada de método `Math.sqrt(5)` como se ela tivesse sido “`magicamente`”
substituída por um `double` que aproxima a raiz quadrada de 5.

=== Sintaxe: Métodos

A esta altura, você já deve ter uma boa noção dos conceitos por trás da chamada e
até mesmo da criação de métodos estáticos e provavelmente está ansioso para usá-
los. No entanto, ainda não descrevemos todos os detalhes da sintaxe dos métodos em Java. Primeiro, descreveremos como você pode criar seus próprios 
métodos estáticos; depois, discutiremos os detalhes da chamada de métodos estáticos; e
, por fim, explicaremos como as _variáveis de classe_ podem ser usadas a partir de diversos
métodos.

==== Definindo métodos

Um método muito simples que a classe `Math` oferece é o `Math.max()`
. Esse método seleciona o maior dos dois valores fornecidos como
entrada.

[source,java]
----
int maximum = Math.max(5, 10);
----

Nesse caso, o valor armazenado em `maximum` é `10`. Apesar de sua
simplicidade, demonstramos o quanto esse método pode ser útil em nossa
solução para o Jogo da Vida de Conway, em <<arrays#arrays>>. Se
quiséssemos escrever esse método nós mesmos, o código seria o seguinte.

[source,java]
----
public static int max(int a, int b) {
    if (a >= b) {
        return a;
    } else {
        return b;
    }
}
----

Mesmo em um método tão pequeno, há muita sintaxe com a qual
preocupar-se. A primeira linha desse método é chamada de _cabeçalho do método
_. A palavra-chave `public` nesse cabeçalho é usada para indicar que qualquer
código, mesmo código de uma classe diferente, pode chamar esse método. Discutiremos
a restrição de acesso a métodos e variáveis mais adiante
neste capítulo. Por enquanto, considere que todo método é `public`.

A palavra-chave `static` indica que esse método é estático. Embora tenhamos
usado o termo _método estático_ muitas vezes, ainda não o definimos
. Um método estático está vinculado a uma classe inteira, não a um objeto específico
dessa classe — ou seja, um método estático pode ser chamado sem fazer referência
a um objeto da classe. Novamente, discutiremos os detalhes de objetos
e classes no próximo capítulo. Por enquanto, todos os métodos são `estáticos`.

A terceira palavra-chave no cabeçalho do método é o já conhecido `int`, que indica o
tipo de retorno do método. Onde quer que esse método seja chamado, ele pode ser
tratado como um valor `int`, pois é isso que ele retorna. Neste
caso, o tipo de retorno é óbvio: o máximo de dois valores `int` deve
também ser um valor `int`. Qualquer tipo pode ser usado como valor de retorno, incluindo
todos os tipos primitivos e quaisquer tipos de referência ou de array. A única
limitação é que um método só pode retornar um único item, mas como
esse item pode ser uma matriz, essa limitação geralmente não é importante. Também é
possível que um método não retorne nada. Nesse caso, a
palavra-chave `void` é usada para o tipo de retorno.

Em seguida, no cabeçalho do método, vem o identificador `max`, que é o nome do
método. Qualquer identificador válido que você possa usar para um nome de variável é
válido também para um nome de método. É importante escolher um nome que seja
legível e dê ao leitor uma ideia clara do que o método faz. Uma
convenção comum é nomear um método usando uma locução verbal, indicando
a operação que está sendo realizada por esse método (por exemplo, `computeTax`).
Assim como os nomes de variáveis, o padrão do Java é usar a notação camel,
começando com uma letra minúscula e colocando em maiúscula a primeira letra de
cada nova palavra no nome.

Após o nome do método, vem a lista de _parâmetros_, separados
por vírgulas. Neste caso, cada parâmetro é do tipo `int`. Você tem liberdade
para nomear seus parâmetros como quiser, embora eles devam ser
significativos. Você pode ter até zero parâmetros, mas há um
limite máximo imposto pela JVM, geralmente 255. O corpo do método
segue o cabeçalho do método, entre chaves (`{ }`). Ao contrário das
instruções `if` e dos laços de repetição, as chaves para métodos são *obrigatórias*.

Dentro do corpo de um método, as regras usuais para o fluxo de controle em Java
se aplicam. Cada linha é executada uma a uma, a menos que haja
instruções de seleção ou repetição. Também é permitido chamar métodos dentro de outros métodos.
No método `max()`, usamos uma construção `if`-`else` para encontrar
o maior valor entre `a` e `b`. Uma instrução `return` interrompe imediatamente
a execução do método, transfere a execução de volta para o código chamador,
e retorna o valor que vem logo a seguir. Nesse caso, o valor de
`a` é retornado se for igual ou maior, e o valor de `b` é
retornado caso contrário. Como uma instrução `return` salta imediatamente
para fora de um método, poderíamos ter escrito o método sem um `else`.

[source,java]
----
public static int max(int a, int b) {
    if (a >= b) {
        return a;
    }
    return b;
}
----

A única maneira de a linha `return b;` ser executada é se `a` ainda não
tivesse sido retornado.

Programadores iniciantes às vezes perguntam o que fazer se `a` e `b` forem iguais. Em nosso código, fica claro que o valor de `a` será retornado, mas isso praticamente não importa: dois valores `int` iguais são indistinguíveis um do outro. Alguns alunos imaginam lidar com esse caso especial exibindo uma mensagem de erro, mas essa abordagem raramente é útil. Ao tentar encontrar o maior de dois números na programação, geralmente é o valor que queremos, e não a informação sobre qual deles é realmente maior.

===== O método `main()`

Se parte dessa sintaxe parecer estranhamente familiar, lembre-se de que você
já vem programando métodos estáticos desde o seu primeiro programa em Java. O
método `main()` é apenas mais um método estático, especial apenas porque a
JVM opta por iniciar a execução a partir dele. Vamos dar uma olhada no método `main()`
de um programa padrão “Hello, World!”.

[source,java]
----
public static void main(String[] args) {
    System.out.println(“Hello, world!”);
    return;
}
----

Assim como o método `max()`, a declaração do `main()` começa com
`public static`. Além disso, o tipo de retorno do `main()` é `void`, pois
a JVM não espera receber nenhum resultado de volta. O método `main()` tem
um único parâmetro: uma matriz de valores do tipo `String`. Neste programa, nós
não usamos o parâmetro `args`, mas ele está disponível. Para o método `main()`
, essa declaração está correta, pois `main()` precisa ser padronizado
em todos os programas. No entanto, ao projetar seus próprios métodos, você
não deve incluir parâmetros desnecessários.

A última linha executável neste método `main()` é uma instrução `return`
. Como `main()` tem tipo de retorno `void`, a instrução `return`
não tem nenhum valor para retornar. Para métodos `void`, uma instrução `return`
é opcional. Você pode usá-la para sair de um método antecipadamente, se
desejar. Para um método que retorna um valor, a execução *deve* chegar a uma instrução `return`
com um valor válido, independentemente da entrada do método.
Se o Java detectar que a execução poderia chegar ao fim de um método que retorna um valor
sem atingir uma instrução `return`, isso causará um
erro de compilação.

===== Métodos sobrecarregados

Como essa declaração está em outra classe, é válido criar um método `max()`
mesmo que já exista um na classe `Math`. No entanto, é possível criar mais de um método com o mesmo nome, mesmo na
mesma classe, desde que suas _assinaturas_ não sejam iguais. Dois
métodos têm a mesma _assinatura_ se tiverem o mesmo nome e
os mesmos tipos de parâmetros.

[source,java]
----
public static int max(int a, int b, int c) {
    return max(max(a, b), c);
}
----

Neste exemplo, criamos mais um método `max()`, mas este
aceita três parâmetros em vez de dois. Esse método chega a chamar a
versão de dois parâmetros do `max()`. Criar mais de um método com o
mesmo nome é chamado de _sobrecarga _ desses métodos. A sobrecarga de métodos é
útil porque permite usar o mesmo nome de método para funcionalidades semelhantes
, mesmo quando há algumas diferenças subjacentes na
implementação. Por exemplo, a classe `Math` fornece quatro versões diferentes,
sobrecarregadas do método `max()`, especializadas para valores `int`,
`long`, `float` e `double`, respectivamente.

É claro que existem limitações na criação de métodos sobrecarregados. O
compilador deve ser capaz de determinar qual método você pretende usar. Portanto,
as assinaturas precisam variar de acordo com o tipo ou o número de parâmetros. Um
tipo de retorno diferente não é suficiente.

==== Chamada de métodos

Depois que um método é definido, ele precisa ser chamado antes de fazer
qualquer coisa. Você já tem bastante experiência em chamar métodos estáticos como
`Math.sqrt()` e `Math.max()`. Um exemplo da sintaxe apropriada foi
apresentado anteriormente.

[source,java]
----
int maximum = Math.max(5, 10);
----

Formalmente, a chamada começa com o nome da classe (`Math`), seguido
por um ponto, seguido pelo nome do método (`max`), seguido pela
lista de _argumentos_ entre parênteses. Esses argumentos são os valores
que você deseja _passar_ para o método. Alguns livros usam o termo _parâmetros formais
para descrever as variáveis definidas na assinatura do método
e _parâmetros reais_ para descrever os valores passados para os métodos,
mas preferimos usar os termos mais simples: parâmetros e argumentos.

É claro que o número de argumentos deve corresponder ao número de parâmetros
definidos pelo método, e os tipos também devem corresponder. O Java realiza
conversão automática quando não há perda de precisão. Assim, você sempre pode fornecer
um argumento `int` para um parâmetro `double`, mas não o contrário.
Os argumentos podem ser valores literais, variáveis ou até mesmo outras chamadas de método
que retornem o tipo apropriado.

Usando o método `max()` definido anteriormente, poderíamos reescrever nosso exemplo simples
sem o nome da classe.

[source,java]
----
int maximum = max(5, 10);
----

Sempre que você chamar um método estático a partir de código que esteja dentro da mesma
classe, poderá omitir o nome da classe.

===== Ligação

Muitos programadores iniciantes ficam confusos quanto à relação entre
argumentos e parâmetros. O processo de fornecer um argumento para ser
usado como parâmetro é chamado de _ligação_. Por meio da ligação, um valor ou
variável do código chamador recebe um novo nome dentro de um método.
Considere o seguinte método.

[source,java]
----
public static int add(int a, int b) {
    return a + b;
}
----

Este método absurdamente curto soma dois números e retorna o
resultado, aproximando-se da funcionalidade do operador `+`. Poderíamos
chamar o método no seguinte contexto.

[source,java]
----
int x = 3;
int y = 5;
int z = add(x, y);
----

Dentro do método, o valor de `x` é vinculado à variável `a`, e
o valor de `y` é vinculado à variável `b`. O método `add()` possui
seu próprio _escopo_. Escopo significa a área onde um nome de variável é visível
(ou significativo). Assim, `x` e `y` não existem dentro do método `add()`
, apenas as variáveis `a` e `b` existem. Como os métodos têm seu próprio
escopo, as variáveis em um método podem ter os mesmos nomes que as variáveis em
outro método sem que o compilador (ou o programador!) fique
confuso. Considere o exemplo a seguir.

[source,java]
----
int a = 3;
int b = 5;
int c = add(b, a);
----

Aqui, as variáveis `a` e `b` existem tanto no código de chamada quanto dentro
do método, mas os nomes são independentes. O valor de `a` no
código de chamada está vinculado a uma variável chamada `b` dentro do
método, mas a JVM não tem nenhuma confusão sobre qual `a` é qual. É nisso
que reside o valor dos métodos: eles são amplamente independentes de tudo o mais
que esteja acontecendo no código, permitindo que o programador se concentre em uma tarefa pequena e
gerenciável.

Outra característica importante do Java é que o processo de vinculação
de variáveis é _passagem por valor_, o que significa que apenas o *valor* do
argumento é vinculado ao parâmetro. Sempre que um método é chamado, o
método cria uma nova variável para cada parâmetro e copia o valor de
seu argumento para ela. Na prática, essa abordagem significa que um método
não pode alterar diretamente o valor de um argumento. Considere o seguinte
método.

[source,java]
----
public static void increment(int counter) {
    ++counter;
}
----

Esse método pega o valor de seu argumento e o copia para a nova
variável `counter`. Em seguida, ele incrementa `counter`, mas o
argumento original permanece inalterado. Portanto, o fragmento a seguir é um laço infinito.

[source,java]
----
int i = 0;
while (i < 100) {
    increment(i);
}
----

O valor de `i` permanece fixo em `0` durante todo o programa. A cópia
de `i` associada a `counter` aumenta para `1` toda vez que `increment()` é
chamado, mas `i` permanece inalterado.

Isso não significa que um método não possa afetar as variáveis fora de
si mesmo. A principal maneira de fazer isso é usando instruções `return`
. Podemos reescrever `increment()` para obter esse efeito.

[source,java]
----
public static int increment(int counter) {
    return counter + 1;
}
----

Em seguida, precisamos ajustar o laço para que ele armazene o valor retornado
em vez de descartá-lo.

[source,java]
----
int i = 0;
while (i < 100) {
    i = increment(i);
}
----

Uma segunda maneira pela qual os métodos podem afetar os valores de variáveis externas é
mais indireta. Em Java, todos os argumentos são passados por valor, mesmo matrizes
e objetos. Na prática, isso significa que, se uma referência a um vetor for
passada para um método, você não pode alterar para qual vetor ela está apontando.
Como as referências não são valores, mas nomes que apontam para
locais específicos na memória, você pode alterar diretamente o conteúdo dessa memória
com um método, mesmo que não possa alterar quais locais estão sendo
referenciados. Por exemplo, o método a seguir *não* inverte a
ordem de um vetor.

[source,java]
----
public static void badReverseArray(int[] array) {
    int[] temp = new int[array.length];
    for (int i = 0; i < array.length; ++i) {
        temp[i] = array[array.length - i - 1];
    }
    array = temp;
}
----

Embora esse código armazene uma versão invertida de `array` em `temp`,
a última linha do método não tem sentido: o array passado para o
método ainda aponta para a localização original na memória. Podemos reescrever
o método para fazer a inversão _no próprio local_, o que significa que os valores do
vetor são reorganizados, mas o vetor ainda ocupa as mesmas
localizações na memória.

[source,java]
----
public static void goodReverseArray(int[] array) {
    int temp;
    for (int i = 0; i < array.length / 2; ++i) {
        temp = array[i];
        array[i] = array[array.length - i - 1];
        
array[array.length - i - 1] = temp;
    }
}
----

Nesta versão do método, trocamos o primeiro elemento da matriz
pelo último, o segundo pelo penúltimo e assim por diante. Só vamos
até a metade da matriz; caso contrário, desfazeríamos o
processo de reversão. Os valores da matriz estão invertidos, mas ainda ocupam o
mesmo bloco de memória. É possível escrever um método correto mais no
estilo de `badReverseArray()`, que cria uma matriz temporária, copia
os valores originais para ela e, em seguida, os copia de volta para a matriz original
na ordem inversa, mas é menos eficiente criar a matriz extra
e realizar duas cópias.

==== Variáveis de classe

De acordo com as regras que apresentamos até agora, as únicas variáveis válidas no
escopo de um método estático são os parâmetros e quaisquer outras variáveis _locais_
declaradas dentro do método. No entanto, é possível criar
uma variável que exista fora dos métodos estáticos, mas que seja visível dentro
de todos eles. Esse tipo de variável é chamado de _variáveis de classe_ (ou
às vezes _campos estáticos_ ou _variáveis globais_). Essas variáveis
persistem *entre* as chamadas de método. A sintaxe para criar tal variável
é declará-la fora de todos os métodos (mas dentro da classe) com a palavra-chave `static` e um modificador de acesso, como `public` ou `private`.
Por exemplo, a classe a seguir inclui um método chamado `record()`
que aumenta a variável de classe `counter` toda vez que é chamado.

.Mantém o controle do número de vezes que o método `record()` é chamado.
[source, java]
[[BookkeeperProgram]]
----
include::{programsdir}/Bookkeeper.java[]
----

Quando executado, este programa chama o método `record()` um número aleatório de
vezes, e a variável `counter` mantém o controle desse número. Como `counter` é estática,
ela é acessível tanto pelo método `main()` quanto pelo `record()`.
Muitos programadores desaprovam o uso de
variáveis de classe justamente porque elas são visíveis a muitos
métodos diferentes. A ideia de um método é isolar trechos de código para que a
complexidade de um programa possa ser dividida em unidades simples. No caso de
uma variável de classe pública, até mesmo o código de outras classes pode modificar seu
valor. Se muitos trechos diferentes de código puderem modificar uma variável, pode
ser difícil impedir que essa variável seja alterada de maneiras inesperadas
. Por exemplo, se outro método usasse a variável `counter` para registrar o número
de vezes que foi chamado, o valor final de `counter` seria a soma
do número de vezes que os dois métodos foram chamados. Pode haver algum
motivo para acompanhar essas informações, mas seria impossível
reconstruir qual fração do valor em `counter` veio de um método
e qual fração veio do outro.

Variáveis de classe têm suas utilidades, mas geralmente devem ser evitadas.
A principal exceção a essa regra são as constantes. Como uma constante nunca muda,
uma variável de classe é um ótimo local para armazená-la, tornando o valor
disponível para todo o código. Um exemplo que você já usou é
`Math.PI`. Assim como nos métodos estáticos, um campo estático de outra classe pode
ser acessado usando o nome da classe, seguido de um ponto e, em seguida, o nome do
campo estático. Novamente, quando o código que usa o campo está na mesma classe,
o nome da classe pode ser omitido. Uma constante de classe é declarada como uma variável de classe
, mas com a adição da palavra-chave `final`.

[[gravitationalAttractionExample]]
.Atração gravitacional
====

A classe a seguir permite que um usuário calcule a força unidimensional devida à gravidade.
Essa força _F_ é dada pela seguinte equação.
//[stem]
//****
//F = \frac{Gm_1m_2}{r^2}
//****

[.text-center]
image::gravitation.svg[scaledwidth=15%,pdfwidth=15%,width=15%]


Nesta equação, _m_~1~ é a massa de um
objeto, _m_~2~ é a massa de outro, _r_ é a
distância entre seus centros e _G_ é a constante gravitacional
, 6,673 × 10^-11^ N·m^2^·kg^-2^.

.Calcula a atração gravitacional entre duas massas.
[source, java]
[[GravityProgram]]
----
include::{programsdir}/Gravity.java[]
----

====

Use constantes nomeadas sempre que elas aumentarem a legibilidade. Você pode usar o modificador `public`
se quiser que todas as classes tenham acesso à sua constante
(`Gravity.G` é um bom exemplo). Você pode usar o modificador `private` se
quiser que a constante seja acessível apenas dentro da sua classe, se ela não tiver
utilidade fora dela ou se contiver informações confidenciais.


=== Exemplos: Definindo métodos

Qualquer problema complexo deve ser dividido em métodos. Como essa
técnica é útil em tantas circunstâncias, é difícil apresentar um
conjunto de exemplos que abranja todos os casos. Em vez disso, nossos exemplos são
métodos curtos e fáceis de entender, com foco na distância euclidiana,
na verificação de palíndromos e na conversão de uma representação `String` de um
`int` para um `int`.

.Distância Euclidiana
====

A distância Euclidiana entre dois pontos é o comprimento da reta
que os une. Ela desempenha um papel importante em gráficos 3D e
jogos e é a base para muitas outras aplicações práticas que envolvem
relações espaciais.

Dados dois pontos no espaço 3D (_x_~1~, _y_~1~, _z_~1~) e
(_x_~2~, _y_~2~, _z_~2~), podemos calcular a distância Euclidiana entre eles com a seguinte
equação.

//[stem]
//****
//d = \sqrt{(x_1 - x_2)^2 + (y_1 - y_2)^2 + (z_1 - z_2)^2}
//****

[.text-center]
image::distance.svg[scaledwidth=55%,pdfwidth=55%,width=55%]

O método abaixo aplica essa equação diretamente.

[source,java]
----
public static double distance(double x1, double y1, double z1,
double x2, double y2, double z2) {
    double x = x1 - x2;
    
double y = y1 - y2;
    double z = z1 - z2;
    return Math.sqrt(x*x + y*y + z*z);
}
----

Essa equação é uma boa candidata a um método estático, já que pode ser
necessário fazer esse cálculo várias vezes e ela não depende de
nenhuma outra variável ou do estado do programa.
====

[[palindromeTestingExample]]
.Teste de palíndromos
====

Um palíndromo é uma palavra ou frase (ou até mesmo um número) que é igual
quando lida para frente e para trás. “`Arara,`”, “`"A dama amada,`” e
“`Socorram-me, subi no ônibus em Marrocos!`” são exemplos em português.
Normalmente, espaços e sinais de pontuação são ignorados. Vamos escrever uma
função que, dada uma `String`, retorne `true` se for um palíndromo
e `false` caso contrário. Para simplificar o problema, *não* vamos
ignorar espaços e sinais de pontuação. Assim, com nosso método, “`arara`” conta
como um palíndromo, mas nenhum dos outros dois exemplos seria considerado como tal.

[source,java]
----
public static boolean isPalindrome(String text) { // <.>
    text = text.toLowerCase(); // <.>
    
for (int i = 0; i < text.length() / 2; ++i) { // <.>
        if (text.charAt(i) != text.charAt(text.length() - i - 1)) { // <.>
            return false;
        }
    }
    return true;
}
----
<.> Como nosso método retorna `true` ou `false`, seu tipo de retorno deve ser
`boolean`. Muitos métodos que retornam um valor `boolean` têm um nome
que começa com `is`, como o nosso método.
<.> A primeira linha do corpo do nosso
método transforma `text` em letras minúsculas.
 
O método `toLowerCase()` da classe `String`
cria uma cópia em letras minúsculas da `String` na qual é chamado, neste caso
`text`. Em seguida, atribuímos à variável de referência `text` essa nova
`String` em letras minúsculas. Fora desta função, a `String` passada como parâmetro
não se altera, pois a referência `text` é passada por valor.
<.> O loop percorre a primeira metade de `text`, comparando-a com a
segunda metade. Esse loop reflete a assimetria desse tipo de teste:
não é possível ter certeza de que `text` é um palíndromo até que se verifique
o texto inteiro, mas sabe-se imediatamente que não é, caso mesmo que um único
par de caracteres não coincida.
<.> Se o teste na instrução `if`
mostrar que os dois valores `char` não são iguais, a instrução `return false`
sai do método sem concluir o loop.
====

****
<<palindromeExercise>>
****

[[parsingANumberExample]]
.Analisando um número
====

Quando você lê um número usando um objeto da classe `Scanner`, ele
converte (ou _analisa_) o texto digitado pelo usuário no tipo apropriado
. Por exemplo, o método `nextDouble()` lê um texto e
o converte em um `double`. Quando você usa um método do `JOptionPane` para ler
uma entrada, ela chega como uma `String`. Se você quiser usar esses dados como um
`double`, você deve convertê-lo usando o método estático `Double.parseDouble()`
. Algum programador Java teve que escrever esse método. Vamos
recriar um método semelhante para converter a representação `String` de um
número de ponto flutuante em um `double`. Nosso método simples ignora
a notação científica.

[source,java]
----
public static double parseDouble(String value) {
    
int i = 0;
    boolean negative = false;
    double temp = 0.0;
    double fraction = 10.0;
    if (value.charAt(i) == ‘-’) { // <.>
        negative = true;
        ++i;
    } else if (value.charAt(i) == ‘+’) {
        ++i;
    }
    
while (i < value.length() && value.charAt(i) != ‘.’) { // <.>
        temp *= 10.0;
        temp += value.charAt(i) - ‘0’;
        ++i;
    }
    ++i; // Passar pela casa decimal (se houver) <.>
    
while (i < value.length()) { // <.>
        temp += (value.charAt(i) - ‘0’) / fraction;
        fraction *= 10.0;
        ++i;
    }
    if (negative) { // <.>
        temp = -temp;
    }
    return temp;
}
----
<.> Após declarar algumas variáveis, este método verifica primeiro o índice `0` na
`String` de entrada `value` para ver se é um `‘-’` ou um `‘+’`. Se for
um `‘-’`, ele define `negative` como `true` e segue em frente. Se for um `‘+’`, ele
simplesmente segue em frente.
<.> Em seguida, o método percorre `value` até chegar
ao fim ou encontrar um ponto decimal. À medida que itera, ele multiplica o
valor atual de `temp` por `10.0` e soma o próximo dígito de `value`
(após subtrair `‘0’` para que o intervalo fique entre 0 e 9).
 
Essa
multiplicação repetitiva por `10.0` representa as potências crescentes de 10
no sistema numérico de base 10. Como `temp` começa com o valor `0.0`,
a primeira multiplicação não tem efeito, conforme pretendido.
<.> Após o primeiro laço `while`, o índice `i` é incrementado uma vez, para pular
a vírgula decimal, se houver. Se não houver ponto decimal, o
laço deve ter sido encerrado porque o fim de `value` foi alcançado.
<.> O segundo laço `while` é executado até o fim de `value`, desta vez somando a cada vez
o valor de cada dígito dividido por `fraction`, que é aumentado por um fator de `10.0`
a cada vez. Isso nos permite somar dígitos fracionários cada vez menores
ao total.
<.> Definimos `temp` como seu oposto se o sinalizador
`negative` tiver sido definido anteriormente e, por fim, retornamos `temp`.

Observe que o método real `Double.parseDouble()` não apenas
aceita valores `String` em notação científica, mas também realiza uma grande
quantidade de verificações de erros. Nosso código trava ou apresenta 
resultados imprecisos ao receber uma `String` vazia, uma `String` contendo caracteres não numéricos
ou uma `String` com mais de um ponto decimal. Além disso,
esse código não utiliza a melhor abordagem para minimizar
erros de precisão de ponto flutuante.
====

****
<<scientificNotationExercise>>
****

=== Solução: Pôquer de três cartas

Aqui apresentamos nossa solução para o problema do pôquer de três cartas. Explicamos
cada método individualmente.

[source, java]
----
include::{programsdir}/ThreeCardPoker.java[linhas=1..11]
----
<.> Antes do início do nosso método `main()`, declaramos várias
constantes de classe. Dois vetores constantes de valores `String` nos fornecem
uma maneira fácil de representar naipes e valores das cartas.
<.> As seis constantes `int`
restantes são usadas para atribuir um prêmio a cada possível
resultado.

Observe que essas constantes podem ser declaradas em qualquer lugar dentro da
classe, desde que estejam fora dos métodos. No entanto, é
comum (e boa prática) declará-las no início da classe.

[source, java]
----
include::{programsdir}/ThreeCardPoker.java[linhas=13..32]
----
<.> No método `main()`, é criado primeiro um vetor que representa um baralho de 52 cartas,
seguido por um vetor que representa as 3 cartas a serem
distribuídas.
<.> O baralho é preenchido sequencialmente e, em seguida, embaralhado por meio de um método.
<.> Em seguida, as três primeiras cartas do baralho são copiadas para a matriz
que representa a mão de cartas.
<.> A pontuação da mão é determinada e
, em seguida, a mão é exibida. Exibimos a mão após determinar a
pontuação porque ela é ordenada durante o processo de determinação da
pontuação, tornando a saída mais fácil de ler.
 
<.> Por fim, imprimimos a
saída apropriada, dependendo da pontuação.

[source, java]
----
include::{programsdir}/ThreeCardPoker.java[linhas=34..42]
----

Este método embaralha o baralho. Sua abordagem consiste em trocar o primeiro elemento
do vetor de cartas por um dos elementos seguintes, escolhido
aleatoriamente. Em seguida, ele troca o segundo elemento do vetor por qualquer um dos
elementos que o seguem, e assim por diante. Se `Math.random()` realmente nos fornecer um
número aleatório gerado uniformemente no intervalo [0,1), o
baralho final embaralhado deverá ser qualquer um dos 52! baralhos possíveis
com igual probabilidade.

[source, java]
----
include::{programsdir}/ThreeCardPoker.java[linhas=44..52]
----
<.> O primeiro desses métodos imprime uma versão legível por humanos de cada
carta em um vetor (em vez de 0 - 51). Ele faz isso usando o segundo e
o terceiro métodos como métodos auxiliares.
<.> O método `getRank()` calcula o valor de
uma carta a partir de seu número. 
<.> O método `getSuit()` calcula o naipe de uma
carta a partir de seu número.

Os índices obtidos desses métodos são usados
para acessar as matrizes `RANKS` e `SUITS`.

Na linguagem C, chamar o equivalente a um método a partir de um método definido anteriormente
requer uma etapa especial de declaração chamada _prototipagem_ antes de ambos os
métodos. Java não apresenta essa complicação, e os métodos `getRank()` e
`getSuit()` compilam e funcionam perfeitamente se forem escritos
acima de `print()` ou abaixo dele dentro da definição da classe.

[source, java]
----
include::{programsdir}/ThreeCardPoker.java[linhas=54..69]
----

Este método calcula a pontuação primeiro classificando a mão e, em seguida,
testando resultados progressivamente piores, começando pelo melhor, um
straight flush. À medida que avança na lista de resultados, ele chama os
métodos apropriados para determinar se uma mão possui uma determinada característica.

[source, java]
----
include::{programsdir}/ThreeCardPoker.java[linhas=71..84]
----


Este código é uma implementação da ordenação por seleção encapsulada em um método.
Observe que este método *altera* os valores dentro do vetor `hand`, embora não possa alterar o vetor para o qual `hand` aponta.
 
O vetor em si é passado por valor, mas seu conteúdo é
efetivamente passado por referência.

[source, java]
----
include::{programsdir}/ThreeCardPoker.java[linhas=86..107]
----
<.> O código em `hasPair()` funciona
verificando se a primeira e a segunda ou a segunda e a terceira cartas têm
o mesmo valor. 


Seria necessária uma condição adicional se as cartas não estivessem ordenadas.
<.> O código em `hasThree()` verifica se todos os valores
são iguais.
<.> O código em `hasFlush()` é igual ao de `hasThree()`
exceto que ele verifica o naipe em vez do valor.
<.> Por fim, `hasStraight()`
verifica se os valores vêm em sequência, com um
caso adicional para lidar com a possibilidade de o ás ser considerado como o valor mais baixo.
Esse teste só funciona porque as cartas foram classificadas anteriormente.

Esses quatro métodos seriam semelhantes, mas mais complexos, para mãos de pôquer de cinco ou
sete cartas.

=== Concorrência: Métodos

Em Java, é impossível ter concorrência sem métodos. Os métodos
são a maneira pela qual dividimos um programa grande em partes gerenciáveis, mas também fazem
parte da sintaxe que o Java usa para criar threads de execução. Cada
thread de execução está associada a um objeto `Thread`; no entanto, criar
o objeto não é suficiente para iniciar a execução de uma nova thread.
Somente quando o método `start()` é chamado no objeto `Thread` é que a
nova thread começa a ser executada.

Espero que você já tenha começado a visualizar a execução de programas Java como
uma seta que fica ao lado de cada linha de código à medida que ela é executada. Essa
seta pode pular para uma opção e ignorar outro código usando as instruções `if` e
`switch`. Usando laços, a seta pode saltar para trás e
executar repetidamente o código que acabou de ser executado. Conforme discutimos neste
capítulo, a seta pode saltar para dentro de um método, executar o código nesse
método e, em seguida, retornar ao seu chamador, voltando exatamente para onde havia parado
antes da chamada.

Quando o método `start()` é chamado em um objeto `Thread`, no entanto, a
seta retorna ao chamador, mas também se divide em uma segunda
seta que, então, executa o método `run()` correspondente e quaisquer outros
métodos que ele chame. Observe que estamos falando de um método chamado em um
objeto `Thread`, não de um método estático chamado na classe como um todo.
Chamar `start()` é um método de instância, o qual discutimos em
<<classes#classes>>. Ao contrário dos métodos estáticos deste capítulo,
um método de instância está vinculado a um objeto específico, mas
a maior parte do que você aprendeu sobre métodos ainda se aplica.

Os métodos têm como objetivo facilitar a programação, dividindo os programas
em partes pequenas o suficiente para serem compreendidas. Um dos únicos perigos reais dos
métodos é o uso de variáveis de classe, conforme mencionado em
<<Variáveis de classe>>. Esse problema se agrava com
múltiplas threads. Com uma única thread, dois ou mais métodos diferentes
podem afetar a mesma variável de classe, talvez de maneiras conflitantes.
Com múltiplas threads, até mesmo o *mesmo* método pode interferir consigo mesmo.

.LCG sem segurança de thread
====

Um gerador congruencial linear (LCG) permite criar uma sequência de
números pseudoaleatórios usando a equação
_x_~i~ = (_ax_~_i_-1~ + _b_) mod _m_, derivando o próximo número do
anterior, e assim por diante.

.Implementa um LCG semelhante ao usado, por vezes, na função `rand()` da linguagem C.
[source, java]
[[UnsafeRandomProgram]]
----
include::{programsdir}/UnsafeRandom.java[]
----

O programa `UnsafeRandom` listado acima sempre gera a mesma
sequência de números pseudoaleatórios, o que pode ser útil para depurar
um programa. No entanto, se duas ou mais threads chamarem `nextInt()`, elas
provavelmente obterão sequências diferentes. Uma thread selecionará alguns dos
números, e a outra selecionará os números que faltam entre eles. Se
cada thread quiser gerar a mesma sequência de números, o método
deve ser reescrito para que receba o número *anterior* da
sequência. Dessa forma, não há estado compartilhado. Lembre-se de que o uso de uma
variável de classe (não final) deve ser evitado sempre que
possível.

.Implementa o mesmo LCG com segurança, exigindo que o chamador forneça o número aleatório anterior.
[source, java]
[[SafeRandomProgram]]
----
include::{programsdir}/SafeRandom.java[]
----

====

.Métodos imprevisíveis
====

Ao forçar cada thread a manter seu próprio estado, corrigimos o problema anterior
. Em <<sincronização#sincronização>>, falaremos sobre o problema muito
mais complicado de duas threads executando um método exatamente ao mesmo
tempo. Quando isso acontece, efeitos muito curiosos podem ocorrer. Considere o
programa a seguir.

.O método `print()` sempre imprime `“Even”` quando executado com uma única thread, mas às vezes pode imprimir `“Odd”` se for chamado repetidamente com várias threads.
[source, java]
[[AlwaysEvenProgram]]
----
include::{programsdir}/AlwaysEven.java[]
----
<.> Com uma única thread em execução, `value` sempre chega a um número par
antes de ser impresso.
<.> Depois disso, ele é incrementado para o próximo número ímpar.

Se duas ou mais threads chamarem o método `print()`, `value` pode
ser alterado em um valor logo antes de a outra thread executar as instruções `if`.
====

=== Exercícios
*Problemas conceituais*

. Descreva três vantagens de dividir longos segmentos de código em
métodos estáticos.
. Você consegue pensar em alguma desvantagem de dividir o código em métodos?
Existem situações em que o uso de um método não é aconselhável?
. Se você quisesse declarar um método estático que calculasse a
média, a mediana e o desvio padrão de um vetor de entrada com valores do tipo `double`
, como você retornaria esses três resultados?
. Considere a seguinte definição de método.
+
[source,java]
----
public static void twice(int i) {
    i = 2 * i;
}
----
+
Quantas vezes o laço a seguir é executado e por quê?
+
[source,java]
----
int x = 2;
while (x < 128) {
    twice(x);
}
----
. Considere as seguintes assinaturas de dois métodos sobrecarregados.
+
[source,java]
----
public static int magic(int rabbit, double hat)
public static int magic(double wand, int spell)
----
+
Qual método seria invocado pela seguinte chamada?
+
[source,java]
----
int x = magic(3, 16);
----
+
E quanto ao seguinte?
+
[source,java]
----
int y = magic(3.2, 16.4);
----
+
Use um compilador para verificar suas respostas.
. A classe a seguir gera uma sequência de números pares. Cada vez que
o método `next()` é chamado, o próximo número par da sequência é
retornado. Qual é o problema de design em usar um campo estático para manter
o controle do próximo valor da sequência?
+
[source,java]
----
public class EvenNumbers {
    private static int counter = 0;

    
public static int next() {
        counter += 2;
        return counter;
    }
}
----

*Exercício de Programação*

. Escreva um método estático chamado `cube()` que receba um único valor `double`
como parâmetro e retorne seu valor elevado ao cubo. Não use o
método `Math.pow()`.
. Implemente um método estático que receba um único valor `int` como
parâmetro e imprima seus dígitos na ordem inversa. Por exemplo, se `103` fosse
passado para esse método, ele imprimiria `301` na tela.
+
Você pode descobrir qual dígito está na casa das unidades de um número calculando
seu resto na divisão por 10. Em seguida, você pode remover o dígito na
casa das unidades dividindo por 10. Não converta o valor `int` em uma `String`.
. Escreva um método estático que receba uma matriz de valores `int` como
parâmetro e retorne `true` se a matriz estiver em ordem crescente e
`false` caso contrário. Compare cada elemento da matriz com o próximo elemento
da matriz. Se o elemento atual for maior que o próximo
elemento, a matriz não está ordenada em ordem crescente. Observe que você só pode
ter certeza de que a matriz está em ordem crescente depois de ter verificado
todos os pares vizinhos.
. Escreva um método estático que calcule o
⌊log~2~ _n_⌋ de um inteiro _n_.
Observe que, se log~2~ _n_ = _x_, também é verdade que
_n_ = 2^_x_^. Em outras palavras, o operador log~2~
indica qual é a potência de 2 de um número. Uma maneira de definir
o log~2~ _n_ é o número de vezes que você precisa dividir
_n_ por 2 para obter 1. Use essa
definição para criar um loop que calcule o valor sem usar nenhuma chamada
à biblioteca `Math`.
+
Aqui estão alguns exemplos dos valores de retorno que seu método deve retornar para
vários valores de entrada de _n_.
+
[.center%autowidth%unbreakable,cols=“5*^”]
|=============================
|_n_ |Valor de retorno | |_n_ |Valor de retorno

|1 |0 | |16 |4
|2 |1 | |100 |6
|4 |2 | |512 |9
|8 |3 | |1000 |9
|10 |3 | |1024 |10
|=============================
. [[palindromeExercise]] Escreva um método que verifique palíndromos como
o método de <<palindromeTestingExample>>, mas que também ignore
sinais de pontuação e espaços. Assim, `“Aí, Lima falou: “Olá, família!”` deve
ser considerado um palíndromo por esse novo método.
. [[scientificNotationExercise]] Adicione ao método `parseDouble()` de
<<parsingANumberExample>> de modo que ele também possa lidar com números na notação científica padrão do Java
, como `7.239e-14`. Observe que o `e` pode estar em maiúscula
ou minúscula, e o expoente pode começar com um sinal de menos (`-`), um sinal de mais (`+`),
ou nenhum dos dois.
. Reimplemente a solução de <<Solução: Pôquer de três cartas>>
de modo que ela utilize uma interface gráfica (GUI) construída com `JOptionPane` para exibir a mão
e os ganhos.
. O pôquer de cinco cartas é uma versão muito mais comum do pôquer do que a
versão de três cartas que discutimos em <<Problema: Pôquer de três cartas>>.
Usando métodos estáticos, implemente um jogo de pôquer para dois jogadores no qual o
baralho é embaralhado e, em seguida, distribuído em duas mãos de cinco cartas cada. Em seguida,
indique qual mão do jogador vence. Com cinco cartas, determinar qual mão
vence é um processo mais complicado. A classificação das várias 
mãos possíveis, da melhor à pior, é a seguinte.
Straight Flush:::
Todas as cinco cartas pertencem ao mesmo naipe e têm valores em ordem sequencial
(com o ás podendo ser a carta mais alta ou mais baixa). Se dois jogadores tiverem straight
flushes, vence aquele com a mão de maior valor. Se ambos tiverem o mesmo valor,
é um empate.
Quarteto:::
Quatro das cinco cartas têm o mesmo valor. Se duas pessoas tiverem um
quarteto, o conjunto de quatro com o valor mais alto vence.
Full House:::
Três das cinco cartas têm o mesmo valor e as outras duas compartilham
outro valor. Se duas pessoas tiverem um full house, o conjunto de
três com o valor mais alto vence.
Flush:::
Todas as cinco cartas têm o mesmo naipe. Se dois jogadores tiverem flushes, o
que tiver a carta mais alta vence. Se a carta mais alta estiver empatada, a próxima
mais alta decide o empate, e assim por diante. Se os dois flushes tiverem exatamente
os mesmos valores, os dois flushes empatam.
Sequência:::
Todas as cinco cartas têm valores em ordem sequencial (com o Ás como carta mais alta
ou mais baixa). Se dois jogadores tiverem sequência, a de valor mais alto
vence. Se ambos tiverem os mesmos valores, há empate.
Trinca:::
Três das cartas têm o mesmo valor. Se dois jogadores tiverem três do
mesmo valor, o conjunto de três com o valor mais alto vence.
Dois pares:::
Um par de cartas tem o mesmo valor e outro par de cartas tem
outro valor. Se dois jogadores tiverem dois pares, o par de maior valor
é o desempate. Se o par de maior valor for o mesmo, o par de menor valor
é o desempate. Se o par de menor valor for o mesmo, a última
carta não emparelhada é o desempate. Se todos os valores das duas mãos forem iguais,
há empate.
Par:::
Um par de cartas tem o mesmo valor. Se dois jogadores tiverem pares, o
valor do par serve como desempate. Se os pares tiverem o mesmo valor, as
cartas restantes em cada mão servem como desempate, em ordem decrescente de valor.
Carta mais alta:::
Se nenhum dos outros casos se aplicar, a carta mais alta determina o valor
da mão. Se duas pessoas tiverem a mesma carta mais alta, as cartas restantes
em cada mão são usadas como critério de desempate, em ordem decrescente de valor.

*Experimentos*

. Em termos de tempo, há uma pequena sobrecarga associada à chamada
de um método e ao retorno de um valor, mas é muito difícil de medir. Escreva um
programa com duas variáveis `int`, `a` e `b`, em que `a` começa com um
valor de `1` e `b` começa com um valor de `2`. Execute um loop `for`
100.000.000 de vezes. Em cada iteração, primeiro aumente o valor de `a` em
o valor de `b` e, em seguida, aumente o valor de `b` em `a`. Cronometre esse
loop com `System.nanoTime()` e, em seguida, imprima o tempo gasto e o
valor de `a`. O valor de `a` não é importante, mas o compilador irá
otimizar as operações matemáticas feitas com `a` e `b`, a menos que imprimamos o valor.
Recomendamos que você execute este programa repetidamente para ter uma noção do
tempo médio de execução.
+
Agora, em vez de usar o operador `+` para somar `a` e `b`, use o
método a seguir.
+
[source,java]
----
public static int add(int a, int b) {
    return a + b;
}
----
+
Mais uma vez, execute seu programa repetidamente com essa modificação. Qual é a
diferença no tempo de execução entre a versão que usa um método e
a versão que faz a soma diretamente?
+
Dependendo da sua JVM, é bem possível que quase não haja
diferença. A JVM realiza muitas otimizações, incluindo _inlining_,
que substitui uma chamada a um método curto pelo código real dentro do
método.